// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for AdminManageGroups controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { OrderDirection, RequestOptions, GroupPagination, GroupBase, GroupInDB, GroupAdminUpdate } from "../models";

@Service()
export class AdminManageGroupsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiAdminGroupsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<GroupPagination>;
    getAllApiAdminGroupsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GroupPagination>>;
    getAllApiAdminGroupsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GroupPagination>>;
    getAllApiAdminGroupsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/groups`;

        let params = new HttpParams();
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createOneApiAdminGroupsPost(groupBase: GroupBase, observe?: 'body', options?: RequestOptions<'json'>): Observable<GroupInDB>;
    createOneApiAdminGroupsPost(groupBase: GroupBase, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GroupInDB>>;
    createOneApiAdminGroupsPost(groupBase: GroupBase, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GroupInDB>>;
    createOneApiAdminGroupsPost(groupBase: GroupBase, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/groups`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: groupBase,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiAdminGroupsItemIdGet(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<GroupInDB>;
    getOneApiAdminGroupsItemIdGet(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GroupInDB>>;
    getOneApiAdminGroupsItemIdGet(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GroupInDB>>;
    getOneApiAdminGroupsItemIdGet(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/groups/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateOneApiAdminGroupsItemIdPut(itemId: string, groupAdminUpdate: GroupAdminUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<GroupInDB>;
    updateOneApiAdminGroupsItemIdPut(itemId: string, groupAdminUpdate: GroupAdminUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GroupInDB>>;
    updateOneApiAdminGroupsItemIdPut(itemId: string, groupAdminUpdate: GroupAdminUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GroupInDB>>;
    updateOneApiAdminGroupsItemIdPut(itemId: string, groupAdminUpdate: GroupAdminUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/groups/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: groupAdminUpdate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteOneApiAdminGroupsItemIdDelete(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<GroupInDB>;
    deleteOneApiAdminGroupsItemIdDelete(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GroupInDB>>;
    deleteOneApiAdminGroupsItemIdDelete(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GroupInDB>>;
    deleteOneApiAdminGroupsItemIdDelete(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/groups/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
