// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for AdminAbout controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, AdminAboutInfo, AppStatistics, CheckAppConfig } from "../models";

@Service()
export class AdminAboutService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAppInfoApiAdminAboutGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<AdminAboutInfo>;
    getAppInfoApiAdminAboutGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AdminAboutInfo>>;
    getAppInfoApiAdminAboutGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AdminAboutInfo>>;
    /** Get general application information */
    getAppInfoApiAdminAboutGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/about`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getAppStatisticsApiAdminAboutStatisticsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<AppStatistics>;
    getAppStatisticsApiAdminAboutStatisticsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AppStatistics>>;
    getAppStatisticsApiAdminAboutStatisticsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AppStatistics>>;
    getAppStatisticsApiAdminAboutStatisticsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/about/statistics`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    checkAppConfigApiAdminAboutCheckGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<CheckAppConfig>;
    checkAppConfigApiAdminAboutCheckGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CheckAppConfig>>;
    checkAppConfigApiAdminAboutCheckGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CheckAppConfig>>;
    checkAppConfigApiAdminAboutCheckGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/about/check`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
