// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for AdminBackups controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, AllBackups, SuccessResponse, FileTokenResponse } from "../models";

@Service()
export class AdminBackupsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiAdminBackupsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<AllBackups>;
    getAllApiAdminBackupsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AllBackups>>;
    getAllApiAdminBackupsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AllBackups>>;
    getAllApiAdminBackupsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/backups`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createOneApiAdminBackupsPost(observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessResponse>;
    createOneApiAdminBackupsPost(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessResponse>>;
    createOneApiAdminBackupsPost(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessResponse>>;
    createOneApiAdminBackupsPost(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/backups`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiAdminBackupsFileNameGet(fileName: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<FileTokenResponse>;
    getOneApiAdminBackupsFileNameGet(fileName: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FileTokenResponse>>;
    getOneApiAdminBackupsFileNameGet(fileName: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FileTokenResponse>>;
    /** Returns a token to download a file */
    getOneApiAdminBackupsFileNameGet(fileName: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/backups/${fileName}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteOneApiAdminBackupsFileNameDelete(fileName: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessResponse>;
    deleteOneApiAdminBackupsFileNameDelete(fileName: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessResponse>>;
    deleteOneApiAdminBackupsFileNameDelete(fileName: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessResponse>>;
    deleteOneApiAdminBackupsFileNameDelete(fileName: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/backups/${fileName}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    uploadOneApiAdminBackupsUploadPost(archive: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessResponse>;
    uploadOneApiAdminBackupsUploadPost(archive: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessResponse>>;
    uploadOneApiAdminBackupsUploadPost(archive: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessResponse>>;
    /** Upload a .zip File to later be imported into Mealie */
    uploadOneApiAdminBackupsUploadPost(archive: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/backups/upload`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (archive !== undefined) {
            formData.append('archive', String(archive));
        }

        return this.httpClient.request('post', url, {
            body: formData,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    importOneApiAdminBackupsFileNameRestorePost(fileName: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessResponse>;
    importOneApiAdminBackupsFileNameRestorePost(fileName: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessResponse>>;
    importOneApiAdminBackupsFileNameRestorePost(fileName: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessResponse>>;
    importOneApiAdminBackupsFileNameRestorePost(fileName: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/backups/${fileName}/restore`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
