// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for AdminMaintenance controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, MaintenanceSummary, MaintenanceStorageDetails, SuccessResponse } from "../models";

@Service()
export class AdminMaintenanceService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getMaintenanceSummaryApiAdminMaintenanceGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<MaintenanceSummary>;
    getMaintenanceSummaryApiAdminMaintenanceGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MaintenanceSummary>>;
    getMaintenanceSummaryApiAdminMaintenanceGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MaintenanceSummary>>;
    /** Get the maintenance summary */
    getMaintenanceSummaryApiAdminMaintenanceGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/maintenance`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getStorageDetailsApiAdminMaintenanceStorageGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<MaintenanceStorageDetails>;
    getStorageDetailsApiAdminMaintenanceStorageGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MaintenanceStorageDetails>>;
    getStorageDetailsApiAdminMaintenanceStorageGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MaintenanceStorageDetails>>;
    getStorageDetailsApiAdminMaintenanceStorageGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/maintenance/storage`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    cleanImagesApiAdminMaintenanceCleanImagesPost(observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessResponse>;
    cleanImagesApiAdminMaintenanceCleanImagesPost(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessResponse>>;
    cleanImagesApiAdminMaintenanceCleanImagesPost(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessResponse>>;
    /** Purges all the images from the filesystem that aren't .webp */
    cleanImagesApiAdminMaintenanceCleanImagesPost(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/maintenance/clean/images`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    cleanTempApiAdminMaintenanceCleanTempPost(observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessResponse>;
    cleanTempApiAdminMaintenanceCleanTempPost(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessResponse>>;
    cleanTempApiAdminMaintenanceCleanTempPost(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessResponse>>;
    cleanTempApiAdminMaintenanceCleanTempPost(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/maintenance/clean/temp`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    cleanRecipeFoldersApiAdminMaintenanceCleanRecipeFoldersPost(observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessResponse>;
    cleanRecipeFoldersApiAdminMaintenanceCleanRecipeFoldersPost(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessResponse>>;
    cleanRecipeFoldersApiAdminMaintenanceCleanRecipeFoldersPost(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessResponse>>;
    /** Deletes all the recipe folders that don't have names that are valid UUIDs */
    cleanRecipeFoldersApiAdminMaintenanceCleanRecipeFoldersPost(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/admin/maintenance/clean/recipe-folders`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
