// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for AppAbout controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, AppInfo, AppStartupInfo, AppTheme } from "../models";

@Service()
export class AppAboutService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAppInfoApiAppAboutGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<AppInfo>;
    getAppInfoApiAppAboutGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AppInfo>>;
    getAppInfoApiAppAboutGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AppInfo>>;
    /** Get general application information */
    getAppInfoApiAppAboutGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/app/about`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getStartupInfoApiAppAboutStartupInfoGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<AppStartupInfo>;
    getStartupInfoApiAppAboutStartupInfoGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AppStartupInfo>>;
    getStartupInfoApiAppAboutStartupInfoGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AppStartupInfo>>;
    /** returns helpful startup information */
    getStartupInfoApiAppAboutStartupInfoGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/app/about/startup-info`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getAppThemeApiAppAboutThemeGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<AppTheme>;
    getAppThemeApiAppAboutThemeGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AppTheme>>;
    getAppThemeApiAppAboutThemeGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AppTheme>>;
    /** Get's the current theme settings */
    getAppThemeApiAppAboutThemeGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/app/about/theme`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
