// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for ExploreRecipes controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { OrderDirection, RequestOptions, PaginationBase_RecipeSummary_, RecipeSuggestionResponse, Recipe_Output } from "../models";

@Service()
export class ExploreRecipesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiExploreGroupsGroupSlugRecipesGet(groupSlug: string, categories?: any, tags?: any, tools?: any, foods?: any, households?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, cookbook?: any, requireAllCategories?: boolean, requireAllTags?: boolean, requireAllTools?: boolean, requireAllFoods?: boolean, search?: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<PaginationBase_RecipeSummary_>;
    getAllApiExploreGroupsGroupSlugRecipesGet(groupSlug: string, categories?: any, tags?: any, tools?: any, foods?: any, households?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, cookbook?: any, requireAllCategories?: boolean, requireAllTags?: boolean, requireAllTools?: boolean, requireAllFoods?: boolean, search?: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PaginationBase_RecipeSummary_>>;
    getAllApiExploreGroupsGroupSlugRecipesGet(groupSlug: string, categories?: any, tags?: any, tools?: any, foods?: any, households?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, cookbook?: any, requireAllCategories?: boolean, requireAllTags?: boolean, requireAllTools?: boolean, requireAllFoods?: boolean, search?: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PaginationBase_RecipeSummary_>>;
    getAllApiExploreGroupsGroupSlugRecipesGet(groupSlug: string, categories?: any, tags?: any, tools?: any, foods?: any, households?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, cookbook?: any, requireAllCategories?: boolean, requireAllTags?: boolean, requireAllTools?: boolean, requireAllFoods?: boolean, search?: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/explore/groups/${groupSlug}/recipes`;

        let params = new HttpParams();
        if (categories != null) {
            params = HttpParamsBuilder.addToHttpParams(params, categories, 'categories');
        }
        if (tags != null) {
            params = HttpParamsBuilder.addToHttpParams(params, tags, 'tags');
        }
        if (tools != null) {
            params = HttpParamsBuilder.addToHttpParams(params, tools, 'tools');
        }
        if (foods != null) {
            params = HttpParamsBuilder.addToHttpParams(params, foods, 'foods');
        }
        if (households != null) {
            params = HttpParamsBuilder.addToHttpParams(params, households, 'households');
        }
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }
        if (cookbook != null) {
            params = HttpParamsBuilder.addToHttpParams(params, cookbook, 'cookbook');
        }
        if (requireAllCategories != null) {
            params = HttpParamsBuilder.addToHttpParams(params, requireAllCategories, 'requireAllCategories');
        }
        if (requireAllTags != null) {
            params = HttpParamsBuilder.addToHttpParams(params, requireAllTags, 'requireAllTags');
        }
        if (requireAllTools != null) {
            params = HttpParamsBuilder.addToHttpParams(params, requireAllTools, 'requireAllTools');
        }
        if (requireAllFoods != null) {
            params = HttpParamsBuilder.addToHttpParams(params, requireAllFoods, 'requireAllFoods');
        }
        if (search != null) {
            params = HttpParamsBuilder.addToHttpParams(params, search, 'search');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    suggestRecipesApiExploreGroupsGroupSlugRecipesSuggestionsGet(groupSlug: string, foods?: any, tools?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, limit?: number, maxMissingFoods?: number, maxMissingTools?: number, includeFoodsOnHand?: boolean, includeToolsOnHand?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeSuggestionResponse>;
    suggestRecipesApiExploreGroupsGroupSlugRecipesSuggestionsGet(groupSlug: string, foods?: any, tools?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, limit?: number, maxMissingFoods?: number, maxMissingTools?: number, includeFoodsOnHand?: boolean, includeToolsOnHand?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeSuggestionResponse>>;
    suggestRecipesApiExploreGroupsGroupSlugRecipesSuggestionsGet(groupSlug: string, foods?: any, tools?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, limit?: number, maxMissingFoods?: number, maxMissingTools?: number, includeFoodsOnHand?: boolean, includeToolsOnHand?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeSuggestionResponse>>;
    suggestRecipesApiExploreGroupsGroupSlugRecipesSuggestionsGet(groupSlug: string, foods?: any, tools?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, limit?: number, maxMissingFoods?: number, maxMissingTools?: number, includeFoodsOnHand?: boolean, includeToolsOnHand?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/explore/groups/${groupSlug}/recipes/suggestions`;

        let params = new HttpParams();
        if (foods != null) {
            params = HttpParamsBuilder.addToHttpParams(params, foods, 'foods');
        }
        if (tools != null) {
            params = HttpParamsBuilder.addToHttpParams(params, tools, 'tools');
        }
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (limit != null) {
            params = HttpParamsBuilder.addToHttpParams(params, limit, 'limit');
        }
        if (maxMissingFoods != null) {
            params = HttpParamsBuilder.addToHttpParams(params, maxMissingFoods, 'maxMissingFoods');
        }
        if (maxMissingTools != null) {
            params = HttpParamsBuilder.addToHttpParams(params, maxMissingTools, 'maxMissingTools');
        }
        if (includeFoodsOnHand != null) {
            params = HttpParamsBuilder.addToHttpParams(params, includeFoodsOnHand, 'includeFoodsOnHand');
        }
        if (includeToolsOnHand != null) {
            params = HttpParamsBuilder.addToHttpParams(params, includeToolsOnHand, 'includeToolsOnHand');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getRecipeApiExploreGroupsGroupSlugRecipesRecipeSlugGet(recipeSlug: string, groupSlug: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Recipe_Output>;
    getRecipeApiExploreGroupsGroupSlugRecipesRecipeSlugGet(recipeSlug: string, groupSlug: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Recipe_Output>>;
    getRecipeApiExploreGroupsGroupSlugRecipesRecipeSlugGet(recipeSlug: string, groupSlug: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Recipe_Output>>;
    getRecipeApiExploreGroupsGroupSlugRecipesRecipeSlugGet(recipeSlug: string, groupSlug: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/explore/groups/${groupSlug}/recipes/${recipeSlug}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
