// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for ExploreTools controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { OrderDirection, RequestOptions, PaginationBase_RecipeTool_, RecipeToolOut } from "../models";

@Service()
export class ExploreToolsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiExploreGroupsGroupSlugOrganizersToolsGet(groupSlug: string, search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<PaginationBase_RecipeTool_>;
    getAllApiExploreGroupsGroupSlugOrganizersToolsGet(groupSlug: string, search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PaginationBase_RecipeTool_>>;
    getAllApiExploreGroupsGroupSlugOrganizersToolsGet(groupSlug: string, search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PaginationBase_RecipeTool_>>;
    getAllApiExploreGroupsGroupSlugOrganizersToolsGet(groupSlug: string, search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/explore/groups/${groupSlug}/organizers/tools`;

        let params = new HttpParams();
        if (search != null) {
            params = HttpParamsBuilder.addToHttpParams(params, search, 'search');
        }
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiExploreGroupsGroupSlugOrganizersToolsItemIdGet(itemId: string, groupSlug: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeToolOut>;
    getOneApiExploreGroupsGroupSlugOrganizersToolsItemIdGet(itemId: string, groupSlug: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeToolOut>>;
    getOneApiExploreGroupsGroupSlugOrganizersToolsItemIdGet(itemId: string, groupSlug: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeToolOut>>;
    getOneApiExploreGroupsGroupSlugOrganizersToolsItemIdGet(itemId: string, groupSlug: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/explore/groups/${groupSlug}/organizers/tools/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
