// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for GroupsAIProviders controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { AIProviderCreate, RequestOptions, AIProviderOut, AIProviderUpdate } from "../models";

@Service()
export class GroupsAIProvidersService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    createAiProviderApiGroupsAiProvidersProvidersPost(aIProviderCreate: AIProviderCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<AIProviderOut>;
    createAiProviderApiGroupsAiProvidersProvidersPost(aIProviderCreate: AIProviderCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AIProviderOut>>;
    createAiProviderApiGroupsAiProvidersProvidersPost(aIProviderCreate: AIProviderCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AIProviderOut>>;
    createAiProviderApiGroupsAiProvidersProvidersPost(aIProviderCreate: AIProviderCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/ai-providers/providers`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: aIProviderCreate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getAiProviderApiGroupsAiProvidersProvidersProviderIdGet(providerId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<AIProviderOut>;
    getAiProviderApiGroupsAiProvidersProvidersProviderIdGet(providerId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AIProviderOut>>;
    getAiProviderApiGroupsAiProvidersProvidersProviderIdGet(providerId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AIProviderOut>>;
    getAiProviderApiGroupsAiProvidersProvidersProviderIdGet(providerId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/ai-providers/providers/${providerId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateAiProviderApiGroupsAiProvidersProvidersProviderIdPut(providerId: string, aIProviderUpdate: AIProviderUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<AIProviderOut>;
    updateAiProviderApiGroupsAiProvidersProvidersProviderIdPut(providerId: string, aIProviderUpdate: AIProviderUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AIProviderOut>>;
    updateAiProviderApiGroupsAiProvidersProvidersProviderIdPut(providerId: string, aIProviderUpdate: AIProviderUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AIProviderOut>>;
    updateAiProviderApiGroupsAiProvidersProvidersProviderIdPut(providerId: string, aIProviderUpdate: AIProviderUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/ai-providers/providers/${providerId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: aIProviderUpdate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteAiProviderApiGroupsAiProvidersProvidersProviderIdDelete(providerId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<AIProviderOut>;
    deleteAiProviderApiGroupsAiProvidersProvidersProviderIdDelete(providerId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<AIProviderOut>>;
    deleteAiProviderApiGroupsAiProvidersProvidersProviderIdDelete(providerId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<AIProviderOut>>;
    deleteAiProviderApiGroupsAiProvidersProvidersProviderIdDelete(providerId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/ai-providers/providers/${providerId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
