// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for GroupsSelfService controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, GroupSummary, OrderDirection, PaginationBase_UserSummary_, UserSummary, ReadGroupPreferences, UpdateGroupPreferences, GroupStorage } from "../models";

@Service()
export class GroupsSelfServiceService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getLoggedInUserGroupApiGroupsSelfGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<GroupSummary>;
    getLoggedInUserGroupApiGroupsSelfGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GroupSummary>>;
    getLoggedInUserGroupApiGroupsSelfGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GroupSummary>>;
    /** Returns the Group Data for the Current User */
    getLoggedInUserGroupApiGroupsSelfGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/self`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getGroupMembersApiGroupsMembersGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<PaginationBase_UserSummary_>;
    getGroupMembersApiGroupsMembersGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PaginationBase_UserSummary_>>;
    getGroupMembersApiGroupsMembersGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PaginationBase_UserSummary_>>;
    /** Returns all users belonging to the current group */
    getGroupMembersApiGroupsMembersGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/members`;

        let params = new HttpParams();
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getGroupMemberApiGroupsMembersUsernameOrIdGet(usernameOrId: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserSummary>;
    getGroupMemberApiGroupsMembersUsernameOrIdGet(usernameOrId: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserSummary>>;
    getGroupMemberApiGroupsMembersUsernameOrIdGet(usernameOrId: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserSummary>>;
    /** Returns a single user belonging to the current group */
    getGroupMemberApiGroupsMembersUsernameOrIdGet(usernameOrId: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/members/${usernameOrId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getGroupPreferencesApiGroupsPreferencesGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadGroupPreferences>;
    getGroupPreferencesApiGroupsPreferencesGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadGroupPreferences>>;
    getGroupPreferencesApiGroupsPreferencesGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadGroupPreferences>>;
    getGroupPreferencesApiGroupsPreferencesGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/preferences`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateGroupPreferencesApiGroupsPreferencesPut(updateGroupPreferences: UpdateGroupPreferences, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadGroupPreferences>;
    updateGroupPreferencesApiGroupsPreferencesPut(updateGroupPreferences: UpdateGroupPreferences, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadGroupPreferences>>;
    updateGroupPreferencesApiGroupsPreferencesPut(updateGroupPreferences: UpdateGroupPreferences, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadGroupPreferences>>;
    updateGroupPreferencesApiGroupsPreferencesPut(updateGroupPreferences: UpdateGroupPreferences, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/preferences`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateGroupPreferences,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getStorageApiGroupsStorageGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<GroupStorage>;
    getStorageApiGroupsStorageGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<GroupStorage>>;
    getStorageApiGroupsStorageGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<GroupStorage>>;
    getStorageApiGroupsStorageGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/storage`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
