// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for GroupsMigrations controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { SupportedMigrations, RequestOptions, ReportSummary } from "../models";

@Service()
export class GroupsMigrationsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    startDataMigrationApiGroupsMigrationsPost(migration_type: SupportedMigrations, archive: string, add_migration_tag?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReportSummary>;
    startDataMigrationApiGroupsMigrationsPost(migration_type: SupportedMigrations, archive: string, add_migration_tag?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReportSummary>>;
    startDataMigrationApiGroupsMigrationsPost(migration_type: SupportedMigrations, archive: string, add_migration_tag?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReportSummary>>;
    startDataMigrationApiGroupsMigrationsPost(migration_type: SupportedMigrations, archive: string, add_migration_tag?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/migrations`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (add_migration_tag !== undefined) {
            formData.append('add_migration_tag', String(add_migration_tag));
        }
        if (migration_type !== undefined) {
            formData.append('migration_type', String(migration_type));
        }
        if (archive !== undefined) {
            formData.append('archive', String(archive));
        }

        return this.httpClient.request('post', url, {
            body: formData,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
