// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for GroupsReports controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ReportSummary, ReportOut } from "../models";

@Service()
export class GroupsReportsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiGroupsReportsGet(reportType?: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<ReportSummary>>;
    getAllApiGroupsReportsGet(reportType?: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<ReportSummary>>>;
    getAllApiGroupsReportsGet(reportType?: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<ReportSummary>>>;
    getAllApiGroupsReportsGet(reportType?: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/reports`;

        let params = new HttpParams();
        if (reportType != null) {
            params = HttpParamsBuilder.addToHttpParams(params, reportType, 'report_type');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiGroupsReportsItemIdGet(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReportOut>;
    getOneApiGroupsReportsItemIdGet(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReportOut>>;
    getOneApiGroupsReportsItemIdGet(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReportOut>>;
    getOneApiGroupsReportsItemIdGet(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/reports/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteOneApiGroupsReportsItemIdDelete(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteOneApiGroupsReportsItemIdDelete(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteOneApiGroupsReportsItemIdDelete(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteOneApiGroupsReportsItemIdDelete(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/groups/reports/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
