// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for HouseholdsMealplans controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { OrderDirection, RequestOptions, PlanEntryPagination, CreatePlanEntry, ReadPlanEntry, CreateRandomEntry, UpdatePlanEntry } from "../models";

@Service()
export class HouseholdsMealplansService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiHouseholdsMealplansGet(startDate?: any, endDate?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<PlanEntryPagination>;
    getAllApiHouseholdsMealplansGet(startDate?: any, endDate?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PlanEntryPagination>>;
    getAllApiHouseholdsMealplansGet(startDate?: any, endDate?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PlanEntryPagination>>;
    getAllApiHouseholdsMealplansGet(startDate?: any, endDate?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/mealplans`;

        let params = new HttpParams();
        if (startDate != null) {
            params = HttpParamsBuilder.addToHttpParams(params, startDate, 'start_date');
        }
        if (endDate != null) {
            params = HttpParamsBuilder.addToHttpParams(params, endDate, 'end_date');
        }
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createOneApiHouseholdsMealplansPost(createPlanEntry: CreatePlanEntry, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadPlanEntry>;
    createOneApiHouseholdsMealplansPost(createPlanEntry: CreatePlanEntry, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadPlanEntry>>;
    createOneApiHouseholdsMealplansPost(createPlanEntry: CreatePlanEntry, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadPlanEntry>>;
    createOneApiHouseholdsMealplansPost(createPlanEntry: CreatePlanEntry, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/mealplans`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createPlanEntry,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getTodaysMealsApiHouseholdsMealplansTodayGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    getTodaysMealsApiHouseholdsMealplansTodayGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    getTodaysMealsApiHouseholdsMealplansTodayGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    getTodaysMealsApiHouseholdsMealplansTodayGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/mealplans/today`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createRandomMealApiHouseholdsMealplansRandomPost(createRandomEntry: CreateRandomEntry, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadPlanEntry>;
    createRandomMealApiHouseholdsMealplansRandomPost(createRandomEntry: CreateRandomEntry, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadPlanEntry>>;
    createRandomMealApiHouseholdsMealplansRandomPost(createRandomEntry: CreateRandomEntry, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadPlanEntry>>;
    /**
     * `create_random_meal` is a route that provides the randomized functionality for mealplaners.
     * It operates by following the rules set out in the household's mealplan settings. If no settings
     * are set, it will return any random meal.
     *
     * Refer to the mealplan settings routes for more information on how rules can be applied
     * to the random meal selector.
     */
    createRandomMealApiHouseholdsMealplansRandomPost(createRandomEntry: CreateRandomEntry, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/mealplans/random`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createRandomEntry,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiHouseholdsMealplansItemIdGet(itemId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadPlanEntry>;
    getOneApiHouseholdsMealplansItemIdGet(itemId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadPlanEntry>>;
    getOneApiHouseholdsMealplansItemIdGet(itemId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadPlanEntry>>;
    getOneApiHouseholdsMealplansItemIdGet(itemId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/mealplans/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateOneApiHouseholdsMealplansItemIdPut(itemId: number, updatePlanEntry: UpdatePlanEntry, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadPlanEntry>;
    updateOneApiHouseholdsMealplansItemIdPut(itemId: number, updatePlanEntry: UpdatePlanEntry, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadPlanEntry>>;
    updateOneApiHouseholdsMealplansItemIdPut(itemId: number, updatePlanEntry: UpdatePlanEntry, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadPlanEntry>>;
    updateOneApiHouseholdsMealplansItemIdPut(itemId: number, updatePlanEntry: UpdatePlanEntry, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/mealplans/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updatePlanEntry,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteOneApiHouseholdsMealplansItemIdDelete(itemId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadPlanEntry>;
    deleteOneApiHouseholdsMealplansItemIdDelete(itemId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadPlanEntry>>;
    deleteOneApiHouseholdsMealplansItemIdDelete(itemId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadPlanEntry>>;
    deleteOneApiHouseholdsMealplansItemIdDelete(itemId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/mealplans/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
