// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for HouseholdsInvitations controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, ReadInviteToken, CreateInviteToken, EmailInvitation, EmailInitationResponse } from "../models";

@Service()
export class HouseholdsInvitationsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getInviteTokensApiHouseholdsInvitationsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<ReadInviteToken>>;
    getInviteTokensApiHouseholdsInvitationsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<ReadInviteToken>>>;
    getInviteTokensApiHouseholdsInvitationsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<ReadInviteToken>>>;
    getInviteTokensApiHouseholdsInvitationsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/invitations`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createInviteTokenApiHouseholdsInvitationsPost(createInviteToken: CreateInviteToken, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadInviteToken>;
    createInviteTokenApiHouseholdsInvitationsPost(createInviteToken: CreateInviteToken, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadInviteToken>>;
    createInviteTokenApiHouseholdsInvitationsPost(createInviteToken: CreateInviteToken, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadInviteToken>>;
    createInviteTokenApiHouseholdsInvitationsPost(createInviteToken: CreateInviteToken, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/invitations`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createInviteToken,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    emailInvitationApiHouseholdsInvitationsEmailPost(emailInvitation: EmailInvitation, observe?: 'body', options?: RequestOptions<'json'>): Observable<EmailInitationResponse>;
    emailInvitationApiHouseholdsInvitationsEmailPost(emailInvitation: EmailInvitation, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<EmailInitationResponse>>;
    emailInvitationApiHouseholdsInvitationsEmailPost(emailInvitation: EmailInvitation, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<EmailInitationResponse>>;
    emailInvitationApiHouseholdsInvitationsEmailPost(emailInvitation: EmailInvitation, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/invitations/email`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: emailInvitation,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
