// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for HouseholdsSelfService controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, HouseholdInDB, HouseholdRecipeSummary, OrderDirection, PaginationBase_UserOut_, ReadHouseholdPreferences, UpdateHouseholdPreferences, SetPermissions, UserOut, HouseholdStatistics } from "../models";

@Service()
export class HouseholdsSelfServiceService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getLoggedInUserHouseholdApiHouseholdsSelfGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<HouseholdInDB>;
    getLoggedInUserHouseholdApiHouseholdsSelfGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<HouseholdInDB>>;
    getLoggedInUserHouseholdApiHouseholdsSelfGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<HouseholdInDB>>;
    /** Returns the Household Data for the Current User */
    getLoggedInUserHouseholdApiHouseholdsSelfGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/self`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getHouseholdRecipeApiHouseholdsSelfRecipesRecipeSlugGet(recipeSlug: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<HouseholdRecipeSummary>;
    getHouseholdRecipeApiHouseholdsSelfRecipesRecipeSlugGet(recipeSlug: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<HouseholdRecipeSummary>>;
    getHouseholdRecipeApiHouseholdsSelfRecipesRecipeSlugGet(recipeSlug: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<HouseholdRecipeSummary>>;
    /** Returns recipe data for the current household */
    getHouseholdRecipeApiHouseholdsSelfRecipesRecipeSlugGet(recipeSlug: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/self/recipes/${recipeSlug}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getHouseholdMembersApiHouseholdsMembersGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<PaginationBase_UserOut_>;
    getHouseholdMembersApiHouseholdsMembersGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<PaginationBase_UserOut_>>;
    getHouseholdMembersApiHouseholdsMembersGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<PaginationBase_UserOut_>>;
    /** Returns all users belonging to the current household */
    getHouseholdMembersApiHouseholdsMembersGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/members`;

        let params = new HttpParams();
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getHouseholdPreferencesApiHouseholdsPreferencesGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadHouseholdPreferences>;
    getHouseholdPreferencesApiHouseholdsPreferencesGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadHouseholdPreferences>>;
    getHouseholdPreferencesApiHouseholdsPreferencesGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadHouseholdPreferences>>;
    getHouseholdPreferencesApiHouseholdsPreferencesGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/preferences`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateHouseholdPreferencesApiHouseholdsPreferencesPut(updateHouseholdPreferences: UpdateHouseholdPreferences, observe?: 'body', options?: RequestOptions<'json'>): Observable<ReadHouseholdPreferences>;
    updateHouseholdPreferencesApiHouseholdsPreferencesPut(updateHouseholdPreferences: UpdateHouseholdPreferences, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ReadHouseholdPreferences>>;
    updateHouseholdPreferencesApiHouseholdsPreferencesPut(updateHouseholdPreferences: UpdateHouseholdPreferences, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ReadHouseholdPreferences>>;
    updateHouseholdPreferencesApiHouseholdsPreferencesPut(updateHouseholdPreferences: UpdateHouseholdPreferences, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/preferences`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: updateHouseholdPreferences,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    setMemberPermissionsApiHouseholdsPermissionsPut(setPermissions: SetPermissions, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserOut>;
    setMemberPermissionsApiHouseholdsPermissionsPut(setPermissions: SetPermissions, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserOut>>;
    setMemberPermissionsApiHouseholdsPermissionsPut(setPermissions: SetPermissions, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserOut>>;
    setMemberPermissionsApiHouseholdsPermissionsPut(setPermissions: SetPermissions, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/permissions`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: setPermissions,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getStatisticsApiHouseholdsStatisticsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<HouseholdStatistics>;
    getStatisticsApiHouseholdsStatisticsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<HouseholdStatistics>>;
    getStatisticsApiHouseholdsStatisticsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<HouseholdStatistics>>;
    getStatisticsApiHouseholdsStatisticsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/statistics`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
