// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for HouseholdsShoppingLists controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { OrderDirection, RequestOptions, ShoppingListPagination, ShoppingListCreate, ShoppingListOut, ShoppingListUpdate, ShoppingListMultiPurposeLabelUpdate, ShoppingListAddRecipeParamsBulk } from "../models";

@Service()
export class HouseholdsShoppingListsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiHouseholdsShoppingListsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShoppingListPagination>;
    getAllApiHouseholdsShoppingListsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShoppingListPagination>>;
    getAllApiHouseholdsShoppingListsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShoppingListPagination>>;
    getAllApiHouseholdsShoppingListsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/shopping/lists`;

        let params = new HttpParams();
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createOneApiHouseholdsShoppingListsPost(shoppingListCreate: ShoppingListCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShoppingListOut>;
    createOneApiHouseholdsShoppingListsPost(shoppingListCreate: ShoppingListCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShoppingListOut>>;
    createOneApiHouseholdsShoppingListsPost(shoppingListCreate: ShoppingListCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShoppingListOut>>;
    createOneApiHouseholdsShoppingListsPost(shoppingListCreate: ShoppingListCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/shopping/lists`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: shoppingListCreate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiHouseholdsShoppingListsItemIdGet(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShoppingListOut>;
    getOneApiHouseholdsShoppingListsItemIdGet(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShoppingListOut>>;
    getOneApiHouseholdsShoppingListsItemIdGet(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShoppingListOut>>;
    getOneApiHouseholdsShoppingListsItemIdGet(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/shopping/lists/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateOneApiHouseholdsShoppingListsItemIdPut(itemId: string, shoppingListUpdate: ShoppingListUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShoppingListOut>;
    updateOneApiHouseholdsShoppingListsItemIdPut(itemId: string, shoppingListUpdate: ShoppingListUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShoppingListOut>>;
    updateOneApiHouseholdsShoppingListsItemIdPut(itemId: string, shoppingListUpdate: ShoppingListUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShoppingListOut>>;
    updateOneApiHouseholdsShoppingListsItemIdPut(itemId: string, shoppingListUpdate: ShoppingListUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/shopping/lists/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: shoppingListUpdate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteOneApiHouseholdsShoppingListsItemIdDelete(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShoppingListOut>;
    deleteOneApiHouseholdsShoppingListsItemIdDelete(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShoppingListOut>>;
    deleteOneApiHouseholdsShoppingListsItemIdDelete(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShoppingListOut>>;
    deleteOneApiHouseholdsShoppingListsItemIdDelete(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/shopping/lists/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateLabelSettingsApiHouseholdsShoppingListsItemIdLabelSettingsPut(itemId: string, requestBody: Array<ShoppingListMultiPurposeLabelUpdate>, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShoppingListOut>;
    updateLabelSettingsApiHouseholdsShoppingListsItemIdLabelSettingsPut(itemId: string, requestBody: Array<ShoppingListMultiPurposeLabelUpdate>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShoppingListOut>>;
    updateLabelSettingsApiHouseholdsShoppingListsItemIdLabelSettingsPut(itemId: string, requestBody: Array<ShoppingListMultiPurposeLabelUpdate>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShoppingListOut>>;
    updateLabelSettingsApiHouseholdsShoppingListsItemIdLabelSettingsPut(itemId: string, requestBody: Array<ShoppingListMultiPurposeLabelUpdate>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/shopping/lists/${itemId}/label-settings`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: requestBody,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    addRecipeIngredientsToListApiHouseholdsShoppingListsItemIdRecipePost(itemId: string, requestBody: Array<ShoppingListAddRecipeParamsBulk>, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShoppingListOut>;
    addRecipeIngredientsToListApiHouseholdsShoppingListsItemIdRecipePost(itemId: string, requestBody: Array<ShoppingListAddRecipeParamsBulk>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShoppingListOut>>;
    addRecipeIngredientsToListApiHouseholdsShoppingListsItemIdRecipePost(itemId: string, requestBody: Array<ShoppingListAddRecipeParamsBulk>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShoppingListOut>>;
    addRecipeIngredientsToListApiHouseholdsShoppingListsItemIdRecipePost(itemId: string, requestBody: Array<ShoppingListAddRecipeParamsBulk>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/shopping/lists/${itemId}/recipe`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: requestBody,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    addSingleRecipeIngredientsToListApiHouseholdsShoppingListsItemIdRecipeRecipeIdPost(itemId: string, recipeId: string, requestBody?: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShoppingListOut>;
    addSingleRecipeIngredientsToListApiHouseholdsShoppingListsItemIdRecipeRecipeIdPost(itemId: string, recipeId: string, requestBody?: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShoppingListOut>>;
    addSingleRecipeIngredientsToListApiHouseholdsShoppingListsItemIdRecipeRecipeIdPost(itemId: string, recipeId: string, requestBody?: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShoppingListOut>>;
    addSingleRecipeIngredientsToListApiHouseholdsShoppingListsItemIdRecipeRecipeIdPost(itemId: string, recipeId: string, requestBody?: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/shopping/lists/${itemId}/recipe/${recipeId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: requestBody,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    removeRecipeIngredientsFromListApiHouseholdsShoppingListsItemIdRecipeRecipeIdDeletePost(itemId: string, recipeId: string, requestBody?: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<ShoppingListOut>;
    removeRecipeIngredientsFromListApiHouseholdsShoppingListsItemIdRecipeRecipeIdDeletePost(itemId: string, recipeId: string, requestBody?: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<ShoppingListOut>>;
    removeRecipeIngredientsFromListApiHouseholdsShoppingListsItemIdRecipeRecipeIdDeletePost(itemId: string, recipeId: string, requestBody?: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<ShoppingListOut>>;
    removeRecipeIngredientsFromListApiHouseholdsShoppingListsItemIdRecipeRecipeIdDeletePost(itemId: string, recipeId: string, requestBody?: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/households/shopping/lists/${itemId}/recipe/${recipeId}/delete`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: requestBody,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
