// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for OrganizerCategories controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { OrderDirection, RequestOptions, RecipeCategoryPagination, CategoryIn, CategoryBase, CategorySummary } from "../models";

@Service()
export class OrganizerCategoriesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiOrganizersCategoriesGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeCategoryPagination>;
    getAllApiOrganizersCategoriesGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeCategoryPagination>>;
    getAllApiOrganizersCategoriesGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeCategoryPagination>>;
    /** Returns a list of available categories in the database */
    getAllApiOrganizersCategoriesGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/categories`;

        let params = new HttpParams();
        if (search != null) {
            params = HttpParamsBuilder.addToHttpParams(params, search, 'search');
        }
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createOneApiOrganizersCategoriesPost(categoryIn: CategoryIn, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createOneApiOrganizersCategoriesPost(categoryIn: CategoryIn, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createOneApiOrganizersCategoriesPost(categoryIn: CategoryIn, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Creates a Category in the database */
    createOneApiOrganizersCategoriesPost(categoryIn: CategoryIn, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/categories`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: categoryIn,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getAllEmptyApiOrganizersCategoriesEmptyGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<CategoryBase>>;
    getAllEmptyApiOrganizersCategoriesEmptyGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<CategoryBase>>>;
    getAllEmptyApiOrganizersCategoriesEmptyGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<CategoryBase>>>;
    /** Returns a list of categories that do not contain any recipes */
    getAllEmptyApiOrganizersCategoriesEmptyGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/categories/empty`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiOrganizersCategoriesItemIdGet(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategorySummary>;
    getOneApiOrganizersCategoriesItemIdGet(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategorySummary>>;
    getOneApiOrganizersCategoriesItemIdGet(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategorySummary>>;
    /** Returns a list of recipes associated with the provided category. */
    getOneApiOrganizersCategoriesItemIdGet(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/categories/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateOneApiOrganizersCategoriesItemIdPut(itemId: string, categoryIn: CategoryIn, observe?: 'body', options?: RequestOptions<'json'>): Observable<CategorySummary>;
    updateOneApiOrganizersCategoriesItemIdPut(itemId: string, categoryIn: CategoryIn, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<CategorySummary>>;
    updateOneApiOrganizersCategoriesItemIdPut(itemId: string, categoryIn: CategoryIn, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<CategorySummary>>;
    /** Updates an existing Tag in the database */
    updateOneApiOrganizersCategoriesItemIdPut(itemId: string, categoryIn: CategoryIn, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/categories/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: categoryIn,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteOneApiOrganizersCategoriesItemIdDelete(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteOneApiOrganizersCategoriesItemIdDelete(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteOneApiOrganizersCategoriesItemIdDelete(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /**
     * Removes a recipe category from the database. Deleting a
     * category does not impact a recipe. The category will be removed
     * from any recipes that contain it
     */
    deleteOneApiOrganizersCategoriesItemIdDelete(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/categories/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneBySlugApiOrganizersCategoriesSlugCategorySlugGet(categorySlug: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    getOneBySlugApiOrganizersCategoriesSlugCategorySlugGet(categorySlug: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    getOneBySlugApiOrganizersCategoriesSlugCategorySlugGet(categorySlug: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Returns a category object with the associated recieps relating to the category */
    getOneBySlugApiOrganizersCategoriesSlugCategorySlugGet(categorySlug: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/categories/slug/${categorySlug}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
