// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for OrganizerTags controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { OrderDirection, RequestOptions, RecipeTagPagination, TagIn, RecipeTagResponse } from "../models";

@Service()
export class OrganizerTagsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiOrganizersTagsGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeTagPagination>;
    getAllApiOrganizersTagsGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeTagPagination>>;
    getAllApiOrganizersTagsGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeTagPagination>>;
    /** Returns a list of available tags in the database */
    getAllApiOrganizersTagsGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/tags`;

        let params = new HttpParams();
        if (search != null) {
            params = HttpParamsBuilder.addToHttpParams(params, search, 'search');
        }
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createOneApiOrganizersTagsPost(tagIn: TagIn, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    createOneApiOrganizersTagsPost(tagIn: TagIn, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    createOneApiOrganizersTagsPost(tagIn: TagIn, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Creates a Tag in the database */
    createOneApiOrganizersTagsPost(tagIn: TagIn, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/tags`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: tagIn,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getEmptyTagsApiOrganizersTagsEmptyGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    getEmptyTagsApiOrganizersTagsEmptyGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    getEmptyTagsApiOrganizersTagsEmptyGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Returns a list of tags that do not contain any recipes */
    getEmptyTagsApiOrganizersTagsEmptyGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/tags/empty`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiOrganizersTagsItemIdGet(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeTagResponse>;
    getOneApiOrganizersTagsItemIdGet(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeTagResponse>>;
    getOneApiOrganizersTagsItemIdGet(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeTagResponse>>;
    /** Returns a list of recipes associated with the provided tag. */
    getOneApiOrganizersTagsItemIdGet(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/tags/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateOneApiOrganizersTagsItemIdPut(itemId: string, tagIn: TagIn, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeTagResponse>;
    updateOneApiOrganizersTagsItemIdPut(itemId: string, tagIn: TagIn, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeTagResponse>>;
    updateOneApiOrganizersTagsItemIdPut(itemId: string, tagIn: TagIn, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeTagResponse>>;
    /** Updates an existing Tag in the database */
    updateOneApiOrganizersTagsItemIdPut(itemId: string, tagIn: TagIn, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/tags/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: tagIn,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteRecipeTagApiOrganizersTagsItemIdDelete(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteRecipeTagApiOrganizersTagsItemIdDelete(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteRecipeTagApiOrganizersTagsItemIdDelete(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /**
     * Removes a recipe tag from the database. Deleting a
     * tag does not impact a recipe. The tag will be removed
     * from any recipes that contain it
     */
    deleteRecipeTagApiOrganizersTagsItemIdDelete(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/tags/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneBySlugApiOrganizersTagsSlugTagSlugGet(tagSlug: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeTagResponse>;
    getOneBySlugApiOrganizersTagsSlugTagSlugGet(tagSlug: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeTagResponse>>;
    getOneBySlugApiOrganizersTagsSlugTagSlugGet(tagSlug: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeTagResponse>>;
    getOneBySlugApiOrganizersTagsSlugTagSlugGet(tagSlug: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/organizers/tags/slug/${tagSlug}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
