// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for RecipesUnits controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { OrderDirection, RequestOptions, IngredientUnitPagination, CreateIngredientUnit, IngredientUnit_Output, MergeUnit, SuccessResponse } from "../models";

@Service()
export class RecipesUnitsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiUnitsGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<IngredientUnitPagination>;
    getAllApiUnitsGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<IngredientUnitPagination>>;
    getAllApiUnitsGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<IngredientUnitPagination>>;
    getAllApiUnitsGet(search?: any, orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/units`;

        let params = new HttpParams();
        if (search != null) {
            params = HttpParamsBuilder.addToHttpParams(params, search, 'search');
        }
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createOneApiUnitsPost(createIngredientUnit: CreateIngredientUnit, observe?: 'body', options?: RequestOptions<'json'>): Observable<IngredientUnit_Output>;
    createOneApiUnitsPost(createIngredientUnit: CreateIngredientUnit, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<IngredientUnit_Output>>;
    createOneApiUnitsPost(createIngredientUnit: CreateIngredientUnit, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<IngredientUnit_Output>>;
    createOneApiUnitsPost(createIngredientUnit: CreateIngredientUnit, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/units`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: createIngredientUnit,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    mergeOneApiUnitsMergePut(mergeUnit: MergeUnit, observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessResponse>;
    mergeOneApiUnitsMergePut(mergeUnit: MergeUnit, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessResponse>>;
    mergeOneApiUnitsMergePut(mergeUnit: MergeUnit, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessResponse>>;
    mergeOneApiUnitsMergePut(mergeUnit: MergeUnit, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/units/merge`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: mergeUnit,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiUnitsItemIdGet(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<IngredientUnit_Output>;
    getOneApiUnitsItemIdGet(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<IngredientUnit_Output>>;
    getOneApiUnitsItemIdGet(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<IngredientUnit_Output>>;
    getOneApiUnitsItemIdGet(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/units/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateOneApiUnitsItemIdPut(itemId: string, createIngredientUnit: CreateIngredientUnit, observe?: 'body', options?: RequestOptions<'json'>): Observable<IngredientUnit_Output>;
    updateOneApiUnitsItemIdPut(itemId: string, createIngredientUnit: CreateIngredientUnit, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<IngredientUnit_Output>>;
    updateOneApiUnitsItemIdPut(itemId: string, createIngredientUnit: CreateIngredientUnit, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<IngredientUnit_Output>>;
    updateOneApiUnitsItemIdPut(itemId: string, createIngredientUnit: CreateIngredientUnit, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/units/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: createIngredientUnit,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteOneApiUnitsItemIdDelete(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<IngredientUnit_Output>;
    deleteOneApiUnitsItemIdDelete(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<IngredientUnit_Output>>;
    deleteOneApiUnitsItemIdDelete(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<IngredientUnit_Output>>;
    deleteOneApiUnitsItemIdDelete(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/units/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
