// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for RecipeBulkActions controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { AssignTags, RequestOptions, AssignSettings, AssignCategories, DeleteRecipes, GroupDataExport, ExportRecipes, SuccessResponse } from "../models";

@Service()
export class RecipeBulkActionsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    bulkTagRecipesApiRecipesBulkActionsTagPost(assignTags: AssignTags, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    bulkTagRecipesApiRecipesBulkActionsTagPost(assignTags: AssignTags, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    bulkTagRecipesApiRecipesBulkActionsTagPost(assignTags: AssignTags, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    bulkTagRecipesApiRecipesBulkActionsTagPost(assignTags: AssignTags, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/bulk-actions/tag`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: assignTags,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    bulkSettingsRecipesApiRecipesBulkActionsSettingsPost(assignSettings: AssignSettings, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    bulkSettingsRecipesApiRecipesBulkActionsSettingsPost(assignSettings: AssignSettings, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    bulkSettingsRecipesApiRecipesBulkActionsSettingsPost(assignSettings: AssignSettings, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    bulkSettingsRecipesApiRecipesBulkActionsSettingsPost(assignSettings: AssignSettings, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/bulk-actions/settings`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: assignSettings,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    bulkCategorizeRecipesApiRecipesBulkActionsCategorizePost(assignCategories: AssignCategories, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    bulkCategorizeRecipesApiRecipesBulkActionsCategorizePost(assignCategories: AssignCategories, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    bulkCategorizeRecipesApiRecipesBulkActionsCategorizePost(assignCategories: AssignCategories, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    bulkCategorizeRecipesApiRecipesBulkActionsCategorizePost(assignCategories: AssignCategories, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/bulk-actions/categorize`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: assignCategories,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    bulkDeleteRecipesApiRecipesBulkActionsDeletePost(deleteRecipes: DeleteRecipes, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    bulkDeleteRecipesApiRecipesBulkActionsDeletePost(deleteRecipes: DeleteRecipes, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    bulkDeleteRecipesApiRecipesBulkActionsDeletePost(deleteRecipes: DeleteRecipes, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    bulkDeleteRecipesApiRecipesBulkActionsDeletePost(deleteRecipes: DeleteRecipes, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/bulk-actions/delete`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: deleteRecipes,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getExportedDataApiRecipesBulkActionsExportGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<GroupDataExport>>;
    getExportedDataApiRecipesBulkActionsExportGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<GroupDataExport>>>;
    getExportedDataApiRecipesBulkActionsExportGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<GroupDataExport>>>;
    getExportedDataApiRecipesBulkActionsExportGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/bulk-actions/export`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    bulkExportRecipesApiRecipesBulkActionsExportPost(exportRecipes: ExportRecipes, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    bulkExportRecipesApiRecipesBulkActionsExportPost(exportRecipes: ExportRecipes, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    bulkExportRecipesApiRecipesBulkActionsExportPost(exportRecipes: ExportRecipes, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    bulkExportRecipesApiRecipesBulkActionsExportPost(exportRecipes: ExportRecipes, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/bulk-actions/export`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: exportRecipes,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getExportedDataTokenApiRecipesBulkActionsExportExportIdDownloadGet(exportId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    getExportedDataTokenApiRecipesBulkActionsExportExportIdDownloadGet(exportId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    getExportedDataTokenApiRecipesBulkActionsExportExportIdDownloadGet(exportId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Returns a token to download a file */
    getExportedDataTokenApiRecipesBulkActionsExportExportIdDownloadGet(exportId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/bulk-actions/export/${exportId}/download`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    purgeExportDataApiRecipesBulkActionsExportPurgeDelete(observe?: 'body', options?: RequestOptions<'json'>): Observable<SuccessResponse>;
    purgeExportDataApiRecipesBulkActionsExportPurgeDelete(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<SuccessResponse>>;
    purgeExportDataApiRecipesBulkActionsExportPurgeDelete(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<SuccessResponse>>;
    /** Remove all exports data, including items on disk without database entry */
    purgeExportDataApiRecipesBulkActionsExportPurgeDelete(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/bulk-actions/export/purge`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
