// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for RecipeTimeline controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { OrderDirection, RequestOptions, RecipeTimelineEventPagination, RecipeTimelineEventIn, RecipeTimelineEventOut, RecipeTimelineEventUpdate, UpdateImageResponse } from "../models";

@Service()
export class RecipeTimelineService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiRecipesTimelineEventsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeTimelineEventPagination>;
    getAllApiRecipesTimelineEventsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeTimelineEventPagination>>;
    getAllApiRecipesTimelineEventsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeTimelineEventPagination>>;
    getAllApiRecipesTimelineEventsGet(orderBy?: any, orderByNullPosition?: any, orderDirection?: OrderDirection, queryFilter?: any, paginationSeed?: any, page?: number, perPage?: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/timeline/events`;

        let params = new HttpParams();
        if (orderBy != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderBy, 'orderBy');
        }
        if (orderByNullPosition != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderByNullPosition, 'orderByNullPosition');
        }
        if (orderDirection != null) {
            params = HttpParamsBuilder.addToHttpParams(params, orderDirection, 'orderDirection');
        }
        if (queryFilter != null) {
            params = HttpParamsBuilder.addToHttpParams(params, queryFilter, 'queryFilter');
        }
        if (paginationSeed != null) {
            params = HttpParamsBuilder.addToHttpParams(params, paginationSeed, 'paginationSeed');
        }
        if (page != null) {
            params = HttpParamsBuilder.addToHttpParams(params, page, 'page');
        }
        if (perPage != null) {
            params = HttpParamsBuilder.addToHttpParams(params, perPage, 'perPage');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createOneApiRecipesTimelineEventsPost(recipeTimelineEventIn: RecipeTimelineEventIn, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeTimelineEventOut>;
    createOneApiRecipesTimelineEventsPost(recipeTimelineEventIn: RecipeTimelineEventIn, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeTimelineEventOut>>;
    createOneApiRecipesTimelineEventsPost(recipeTimelineEventIn: RecipeTimelineEventIn, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeTimelineEventOut>>;
    createOneApiRecipesTimelineEventsPost(recipeTimelineEventIn: RecipeTimelineEventIn, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/timeline/events`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: recipeTimelineEventIn,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiRecipesTimelineEventsItemIdGet(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeTimelineEventOut>;
    getOneApiRecipesTimelineEventsItemIdGet(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeTimelineEventOut>>;
    getOneApiRecipesTimelineEventsItemIdGet(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeTimelineEventOut>>;
    getOneApiRecipesTimelineEventsItemIdGet(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/timeline/events/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateOneApiRecipesTimelineEventsItemIdPut(itemId: string, recipeTimelineEventUpdate: RecipeTimelineEventUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeTimelineEventOut>;
    updateOneApiRecipesTimelineEventsItemIdPut(itemId: string, recipeTimelineEventUpdate: RecipeTimelineEventUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeTimelineEventOut>>;
    updateOneApiRecipesTimelineEventsItemIdPut(itemId: string, recipeTimelineEventUpdate: RecipeTimelineEventUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeTimelineEventOut>>;
    updateOneApiRecipesTimelineEventsItemIdPut(itemId: string, recipeTimelineEventUpdate: RecipeTimelineEventUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/timeline/events/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: recipeTimelineEventUpdate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteOneApiRecipesTimelineEventsItemIdDelete(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeTimelineEventOut>;
    deleteOneApiRecipesTimelineEventsItemIdDelete(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeTimelineEventOut>>;
    deleteOneApiRecipesTimelineEventsItemIdDelete(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeTimelineEventOut>>;
    deleteOneApiRecipesTimelineEventsItemIdDelete(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/timeline/events/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateEventImageApiRecipesTimelineEventsItemIdImagePut(itemId: string, image: string, extension: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UpdateImageResponse>;
    updateEventImageApiRecipesTimelineEventsItemIdImagePut(itemId: string, image: string, extension: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UpdateImageResponse>>;
    updateEventImageApiRecipesTimelineEventsItemIdImagePut(itemId: string, image: string, extension: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UpdateImageResponse>>;
    updateEventImageApiRecipesTimelineEventsItemIdImagePut(itemId: string, image: string, extension: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/timeline/events/${itemId}/image`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Remove Content-Type for multipart (browser will set it with boundary)
        headers = headers.delete('Content-Type');

        const formData = new FormData();
        if (image !== undefined) {
            formData.append('image', String(image));
        }
        if (extension !== undefined) {
            formData.append('extension', String(extension));
        }

        return this.httpClient.request('put', url, {
            body: formData,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
