// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for RecipeShared controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, Recipe_Output } from "../models";

@Service()
export class RecipeSharedService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getSharedRecipeApiRecipesSharedTokenIdGet(tokenId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<Recipe_Output>;
    getSharedRecipeApiRecipesSharedTokenIdGet(tokenId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Recipe_Output>>;
    getSharedRecipeApiRecipesSharedTokenIdGet(tokenId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Recipe_Output>>;
    getSharedRecipeApiRecipesSharedTokenIdGet(tokenId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/shared/${tokenId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getSharedRecipeAsZipApiRecipesSharedTokenIdZipGet(tokenId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    getSharedRecipeAsZipApiRecipesSharedTokenIdZipGet(tokenId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    getSharedRecipeAsZipApiRecipesSharedTokenIdZipGet(tokenId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Get a recipe and its original image as a Zip file */
    getSharedRecipeAsZipApiRecipesSharedTokenIdZipGet(tokenId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/shared/${tokenId}/zip`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
