// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for RecipeExports controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, FormatResponse } from "../models";

@Service()
export class RecipeExportsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getRecipeFormatsAndTemplatesApiRecipesExportsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<FormatResponse>;
    getRecipeFormatsAndTemplatesApiRecipesExportsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<FormatResponse>>;
    getRecipeFormatsAndTemplatesApiRecipesExportsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<FormatResponse>>;
    getRecipeFormatsAndTemplatesApiRecipesExportsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/exports`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getRecipeAsFormatApiRecipesSlugExportsGet(slug: string, templateName: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    getRecipeAsFormatApiRecipesSlugExportsGet(slug: string, templateName: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    getRecipeAsFormatApiRecipesSlugExportsGet(slug: string, templateName: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /**
     * ## Parameters
     * `template_name`: The name of the template to use to use in the exports listed. Template type will automatically
     * be set on the backend. Because of this, it's important that your templates have unique names. See available
     * names and formats in the /api/recipes/exports endpoint.
     */
    getRecipeAsFormatApiRecipesSlugExportsGet(slug: string, templateName: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/recipes/${slug}/exports`;

        let params = new HttpParams();
        if (templateName != null) {
            params = HttpParamsBuilder.addToHttpParams(params, templateName, 'template_name');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
