// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for SharedRecipes controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, RecipeShareTokenSummary, RecipeShareTokenCreate, RecipeShareToken } from "../models";

@Service()
export class SharedRecipesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getAllApiSharedRecipesGet(recipeId?: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<RecipeShareTokenSummary>>;
    getAllApiSharedRecipesGet(recipeId?: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<RecipeShareTokenSummary>>>;
    getAllApiSharedRecipesGet(recipeId?: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<RecipeShareTokenSummary>>>;
    getAllApiSharedRecipesGet(recipeId?: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/shared/recipes`;

        let params = new HttpParams();
        if (recipeId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, recipeId, 'recipe_id');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    createOneApiSharedRecipesPost(recipeShareTokenCreate: RecipeShareTokenCreate, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeShareToken>;
    createOneApiSharedRecipesPost(recipeShareTokenCreate: RecipeShareTokenCreate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeShareToken>>;
    createOneApiSharedRecipesPost(recipeShareTokenCreate: RecipeShareTokenCreate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeShareToken>>;
    createOneApiSharedRecipesPost(recipeShareTokenCreate: RecipeShareTokenCreate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/shared/recipes`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: recipeShareTokenCreate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getOneApiSharedRecipesItemIdGet(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<RecipeShareToken>;
    getOneApiSharedRecipesItemIdGet(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<RecipeShareToken>>;
    getOneApiSharedRecipesItemIdGet(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<RecipeShareToken>>;
    getOneApiSharedRecipesItemIdGet(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/shared/recipes/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteOneApiSharedRecipesItemIdDelete(itemId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    deleteOneApiSharedRecipesItemIdDelete(itemId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    deleteOneApiSharedRecipesItemIdDelete(itemId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    deleteOneApiSharedRecipesItemIdDelete(itemId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/shared/recipes/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
