// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for UsersTokens controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { LongLiveTokenIn, RequestOptions, LongLiveTokenCreateResponse, DeleteTokenResponse } from "../models";

@Service()
export class UsersTokensService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    createApiTokenApiUsersApiTokensPost(longLiveTokenIn: LongLiveTokenIn, observe?: 'body', options?: RequestOptions<'json'>): Observable<LongLiveTokenCreateResponse>;
    createApiTokenApiUsersApiTokensPost(longLiveTokenIn: LongLiveTokenIn, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LongLiveTokenCreateResponse>>;
    createApiTokenApiUsersApiTokensPost(longLiveTokenIn: LongLiveTokenIn, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LongLiveTokenCreateResponse>>;
    /** Create api_token in the Database */
    createApiTokenApiUsersApiTokensPost(longLiveTokenIn: LongLiveTokenIn, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/api-tokens`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: longLiveTokenIn,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    deleteApiTokenApiUsersApiTokensTokenIdDelete(tokenId: number, observe?: 'body', options?: RequestOptions<'json'>): Observable<DeleteTokenResponse>;
    deleteApiTokenApiUsersApiTokensTokenIdDelete(tokenId: number, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<DeleteTokenResponse>>;
    deleteApiTokenApiUsersApiTokensTokenIdDelete(tokenId: number, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<DeleteTokenResponse>>;
    /** Delete api_token from the Database */
    deleteApiTokenApiUsersApiTokensTokenIdDelete(tokenId: number, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/api-tokens/${tokenId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
