// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for UsersAuthentication controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, MealieAuthToken, OIDCNativeConfig, NativeOIDCTokenRequest, LogoutResponse } from "../models";

@Service()
export class UsersAuthenticationService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getTokenApiAuthTokenPost(username?: string, password?: string, remember_me?: boolean, observe?: 'body', options?: RequestOptions<'json'>): Observable<MealieAuthToken>;
    getTokenApiAuthTokenPost(username?: string, password?: string, remember_me?: boolean, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MealieAuthToken>>;
    getTokenApiAuthTokenPost(username?: string, password?: string, remember_me?: boolean, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MealieAuthToken>>;
    getTokenApiAuthTokenPost(username?: string, password?: string, remember_me?: boolean, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/token`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for URL-encoded form data
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/x-www-form-urlencoded');
        }

        const formBody = new URLSearchParams();
        if (username !== undefined && username !== null) {
            formBody.append('username', String(username));
        }
        if (password !== undefined && password !== null) {
            formBody.append('password', String(password));
        }
        if (remember_me !== undefined && remember_me !== null) {
            formBody.append('remember_me', String(remember_me));
        }

        return this.httpClient.request('post', url, {
            body: formBody.toString(),
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    oauthLoginApiAuthOauthGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    oauthLoginApiAuthOauthGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    oauthLoginApiAuthOauthGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    oauthLoginApiAuthOauthGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/oauth`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    oauthCallbackApiAuthOauthCallbackGet(code?: any, state?: any, observe?: 'body', options?: RequestOptions<'json'>): Observable<MealieAuthToken>;
    oauthCallbackApiAuthOauthCallbackGet(code?: any, state?: any, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MealieAuthToken>>;
    oauthCallbackApiAuthOauthCallbackGet(code?: any, state?: any, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MealieAuthToken>>;
    oauthCallbackApiAuthOauthCallbackGet(code?: any, state?: any, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/oauth/callback`;

        let params = new HttpParams();
        if (code != null) {
            params = HttpParamsBuilder.addToHttpParams(params, code, 'code');
        }
        if (state != null) {
            params = HttpParamsBuilder.addToHttpParams(params, state, 'state');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    oauthNativeConfigApiAuthOauthNativeConfigGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<OIDCNativeConfig>;
    oauthNativeConfigApiAuthOauthNativeConfigGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<OIDCNativeConfig>>;
    oauthNativeConfigApiAuthOauthNativeConfigGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<OIDCNativeConfig>>;
    /** Return the parameters a native client needs to build its own OIDC authorization request. */
    oauthNativeConfigApiAuthOauthNativeConfigGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/oauth/native/config`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    oauthNativeTokenApiAuthOauthNativeTokenPost(nativeOIDCTokenRequest: NativeOIDCTokenRequest, observe?: 'body', options?: RequestOptions<'json'>): Observable<MealieAuthToken>;
    oauthNativeTokenApiAuthOauthNativeTokenPost(nativeOIDCTokenRequest: NativeOIDCTokenRequest, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MealieAuthToken>>;
    oauthNativeTokenApiAuthOauthNativeTokenPost(nativeOIDCTokenRequest: NativeOIDCTokenRequest, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MealieAuthToken>>;
    /**
     * Exchange a native client's authorization code for a Mealie token.
     *
     * The native client owns PKCE and state, so the exchange happens server-side without a browser
     * session cookie. This lets passkey-capable system-browser logins (e.g. Pocket ID) work, which
     * the cookie-coupled web callback cannot support.
     */
    oauthNativeTokenApiAuthOauthNativeTokenPost(nativeOIDCTokenRequest: NativeOIDCTokenRequest, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/oauth/native/token`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: nativeOIDCTokenRequest,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    refreshTokenApiAuthRefreshGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<MealieAuthToken>;
    refreshTokenApiAuthRefreshGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<MealieAuthToken>>;
    refreshTokenApiAuthRefreshGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<MealieAuthToken>>;
    /** Use a valid token to get another token */
    refreshTokenApiAuthRefreshGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/refresh`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    logoutApiAuthLogoutPost(observe?: 'body', options?: RequestOptions<'json'>): Observable<LogoutResponse>;
    logoutApiAuthLogoutPost(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<LogoutResponse>>;
    logoutApiAuthLogoutPost(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<LogoutResponse>>;
    logoutApiAuthLogoutPost(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/auth/logout`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
