// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for UsersCRUD controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, UserOut, UserRatings_UserRatingSummary_, UserRatingSummary, ChangePassword, Mealie_Schema_User_User__UserBase } from "../models";

@Service()
export class UsersCRUDService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getLoggedInUserApiUsersSelfGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<UserOut>;
    getLoggedInUserApiUsersSelfGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserOut>>;
    getLoggedInUserApiUsersSelfGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserOut>>;
    getLoggedInUserApiUsersSelfGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/self`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getLoggedInUserRatingsApiUsersSelfRatingsGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<UserRatings_UserRatingSummary_>;
    getLoggedInUserRatingsApiUsersSelfRatingsGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserRatings_UserRatingSummary_>>;
    getLoggedInUserRatingsApiUsersSelfRatingsGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserRatings_UserRatingSummary_>>;
    getLoggedInUserRatingsApiUsersSelfRatingsGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/self/ratings`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getLoggedInUserRatingForRecipeApiUsersSelfRatingsRecipeIdGet(recipeId: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserRatingSummary>;
    getLoggedInUserRatingForRecipeApiUsersSelfRatingsRecipeIdGet(recipeId: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserRatingSummary>>;
    getLoggedInUserRatingForRecipeApiUsersSelfRatingsRecipeIdGet(recipeId: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserRatingSummary>>;
    getLoggedInUserRatingForRecipeApiUsersSelfRatingsRecipeIdGet(recipeId: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/self/ratings/${recipeId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getLoggedInUserFavoritesApiUsersSelfFavoritesGet(observe?: 'body', options?: RequestOptions<'json'>): Observable<UserRatings_UserRatingSummary_>;
    getLoggedInUserFavoritesApiUsersSelfFavoritesGet(observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserRatings_UserRatingSummary_>>;
    getLoggedInUserFavoritesApiUsersSelfFavoritesGet(observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserRatings_UserRatingSummary_>>;
    getLoggedInUserFavoritesApiUsersSelfFavoritesGet(observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/self/favorites`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updatePasswordApiUsersPasswordPut(changePassword: ChangePassword, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    updatePasswordApiUsersPasswordPut(changePassword: ChangePassword, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    updatePasswordApiUsersPasswordPut(changePassword: ChangePassword, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Resets the User Password */
    updatePasswordApiUsersPasswordPut(changePassword: ChangePassword, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/password`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: changePassword,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    updateUserApiUsersItemIdPut(itemId: string, mealieSchemaUserUserUserBase: Mealie_Schema_User_User__UserBase, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    updateUserApiUsersItemIdPut(itemId: string, mealieSchemaUserUserUserBase: Mealie_Schema_User_User__UserBase, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    updateUserApiUsersItemIdPut(itemId: string, mealieSchemaUserUserUserBase: Mealie_Schema_User_User__UserBase, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    updateUserApiUsersItemIdPut(itemId: string, mealieSchemaUserUserUserBase: Mealie_Schema_User_User__UserBase, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/${itemId}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('put', url, {
            body: mealieSchemaUserUserUserBase,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
