// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for UsersRatings controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Service } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, UserRatings_UserRatingOut_, UserRatingUpdate } from "../models";

@Service()
export class UsersRatingsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    getRatingsApiUsersIdRatingsGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserRatings_UserRatingOut_>;
    getRatingsApiUsersIdRatingsGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserRatings_UserRatingOut_>>;
    getRatingsApiUsersIdRatingsGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserRatings_UserRatingOut_>>;
    /** Get user's rated recipes */
    getRatingsApiUsersIdRatingsGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/${id}/ratings`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    getFavoritesApiUsersIdFavoritesGet(id: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<UserRatings_UserRatingOut_>;
    getFavoritesApiUsersIdFavoritesGet(id: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<UserRatings_UserRatingOut_>>;
    getFavoritesApiUsersIdFavoritesGet(id: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<UserRatings_UserRatingOut_>>;
    /** Get user's favorited recipes */
    getFavoritesApiUsersIdFavoritesGet(id: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/${id}/favorites`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('get', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    setRatingApiUsersIdRatingsSlugPost(id: string, slug: string, userRatingUpdate: UserRatingUpdate, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    setRatingApiUsersIdRatingsSlugPost(id: string, slug: string, userRatingUpdate: UserRatingUpdate, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    setRatingApiUsersIdRatingsSlugPost(id: string, slug: string, userRatingUpdate: UserRatingUpdate, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Sets the user's rating for a recipe */
    setRatingApiUsersIdRatingsSlugPost(id: string, slug: string, userRatingUpdate: UserRatingUpdate, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/${id}/ratings/${slug}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }
        // Set Content-Type for JSON requests if not already set
        if (!headers.has('Content-Type')) {
            headers = headers.set('Content-Type', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: userRatingUpdate,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    addFavoriteApiUsersIdFavoritesSlugPost(id: string, slug: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    addFavoriteApiUsersIdFavoritesSlugPost(id: string, slug: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    addFavoriteApiUsersIdFavoritesSlugPost(id: string, slug: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Adds a recipe to the user's favorites */
    addFavoriteApiUsersIdFavoritesSlugPost(id: string, slug: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/${id}/favorites/${slug}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('post', url, {
            body: null,
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }

    removeFavoriteApiUsersIdFavoritesSlugDelete(id: string, slug: string, observe?: 'body', options?: RequestOptions<'json'>): Observable<any>;
    removeFavoriteApiUsersIdFavoritesSlugDelete(id: string, slug: string, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<any>>;
    removeFavoriteApiUsersIdFavoritesSlugDelete(id: string, slug: string, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<any>>;
    /** Removes a recipe from the user's favorites */
    removeFavoriteApiUsersIdFavoritesSlugDelete(id: string, slug: string, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/users/${id}/favorites/${slug}`;

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Advertise the response content type declared in the spec
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        return this.httpClient.request('delete', url, {
            observe,
            headers,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        });
    }
}
