import { GeneratorConfig, IPluginGenerator, PluginGeneratorContext } from "ng-openapi";

/**
 * Patches the generated RelationalOperator enum so that special-character
 * values (=, <>, etc.) get valid TypeScript member names.
 */
class RelationalOperatorPlugin implements IPluginGenerator {
  private readonly context: PluginGeneratorContext;

  constructor(context: PluginGeneratorContext) {
    this.context = context;
  }

  async generate(outputRoot: string): Promise<void> {
    const file = this.context.project.createSourceFile(
      `${outputRoot}/models/relational-operator.ts`,
      `/* eslint-disable */
/* @formatter:off */
/**
 * Generated by ng-openapi, patched by RelationalOperatorPlugin.
 * Do not edit this file manually — it is overwritten on every generation.
 */
export enum RelationalOperator {
  EQ = "=",
  NOTEQ = "<>",
  GT = ">",
  LT = "<",
  GTE = ">=",
  LTE = "<="
}
`,
      { overwrite: true },
    );
    file.formatText();
    file.saveSync();
  }
}

const config: GeneratorConfig = {
  // Points to the running Mealie backend's OpenAPI spec.
  // Requires the backend to be running (task py → http://localhost:9000)
  input: "http://localhost:9000/openapi.json",
  output: "./src/api",
  plugins: [RelationalOperatorPlugin],
  options: {
    dateType: "Date",
    enumStyle: "enum",
    generateServices: true,
    serviceDecorator: "service",
    modelFileStructure: "per-type",
  },
};

export default config;
