// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface AdminAboutInfo {
    production: boolean;
    version: string;
    demoStatus: boolean;
    allowSignup: boolean;
    allowPasswordLogin: boolean;
    defaultGroupSlug?: string | null;
    defaultHouseholdSlug?: string | null;
    enableOidc: boolean;
    oidcRedirect: boolean;
    oidcProviderName: string;
    tokenTime: number;
    allowedIframeHosts?: Array<string>;
    versionLatest: string;
    apiPort: number;
    apiDocs: boolean;
    dbType: string;
    dbUrl?: string | null;
    defaultGroup: string;
    defaultHousehold: string;
    buildId: string;
    recipeScraperVersion: string;
}
