// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { AIProviderSummary } from "./aiprovider-summary";
export interface AIProviderSettingsOut {
    defaultProviderId: string | null;
    audioProviderId: string | null;
    imageProviderId: string | null;
    providers: Array<AIProviderSummary>;
    readonly aiEnabled: boolean;
    readonly audioProviderEnabled: boolean;
    readonly imageProviderEnabled: boolean;
}
