// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface AIProviderOut {
    name: string;
    baseUrl?: string | null;
    model: string;
    timeout?: number;
    requestHeaders?: Record<string, string>;
    requestParams?: Record<string, string>;
    id: string;
}
