// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { BackupFile } from "./backup-file";
export interface AllBackups {
    imports: Array<BackupFile>;
    templates: Array<string>;
}
