// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface AppInfo {
    production: boolean;
    version: string;
    demoStatus: boolean;
    allowSignup: boolean;
    allowPasswordLogin: boolean;
    defaultGroupSlug?: string | null;
    defaultHouseholdSlug?: string | null;
    enableOidc: boolean;
    oidcRedirect: boolean;
    oidcProviderName: string;
    tokenTime: number;
    allowedIframeHosts?: Array<string>;
}
