// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface AppStatistics {
    totalRecipes: number;
    totalUsers: number;
    totalHouseholds: number;
    totalGroups: number;
    uncategorizedRecipes: number;
    untaggedRecipes: number;
}
