// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface AppTheme {
    lightPrimary?: string;
    lightAccent?: string;
    lightSecondary?: string;
    lightSuccess?: string;
    lightInfo?: string;
    lightWarning?: string;
    lightError?: string;
    darkPrimary?: string;
    darkAccent?: string;
    darkSecondary?: string;
    darkSuccess?: string;
    darkInfo?: string;
    darkWarning?: string;
    darkError?: string;
}
