// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { TagBase } from "./tag-base";
export interface AssignTags {
    recipes: Array<string>;
    tags: Array<TagBase>;
}
