// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeSettings } from "./recipe-settings";
export interface AssignSettings {
    recipes: Array<string>;
    settings: RecipeSettings;
}
