// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { CategoryBase } from "./category-base";
export interface AssignCategories {
    recipes: Array<string>;
    categories: Array<CategoryBase>;
}
