// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface BodyTriggerActionApiHouseholdsRecipeActions_ItemId_Trigger_RecipeSlug_Post {
    recipe_scale?: number;
}
