// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface BodyCreateRecipeWithAiApiRecipesCreateAiPost {
    content?: string | null;
    url?: string | null;
    translateLanguage?: string | null;
    createNewOrganizers?: boolean;
    images?: Array<string>;
}
