// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface BodyGetTokenApiAuthTokenPost {
    username?: string;
    password?: string;
    remember_me?: boolean;
}
