// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { SupportedMigrations } from "./supported-migrations";
export interface BodyStartDataMigrationApiGroupsMigrationsPost {
    add_migration_tag?: boolean;
    migration_type: SupportedMigrations;
    archive: string;
}
