// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface CheckAppConfig {
    emailReady: boolean;
    ldapReady: boolean;
    ldapDisabled: boolean;
    oidcReady: boolean;
    oidcDisabled: boolean;
    baseUrlSet: boolean;
    isUpToDate: boolean;
}
