// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ReadCookBook } from "./read-cook-book";
export interface CookBookPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<ReadCookBook>;
    next?: string | null;
    previous?: string | null;
}
