// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { CreateIngredientFoodAlias } from "./create-ingredient-food-alias";
export interface CreateIngredientFood {
    id?: string | null;
    name: string;
    pluralName?: string | null;
    description?: string;
    extras?: Record<string, unknown> | null;
    labelId?: string | null;
    aliases?: Array<CreateIngredientFoodAlias>;
    householdsWithIngredientFood?: Array<string>;
}
