// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeCategory } from "./recipe-category";
import { RecipeTag } from "./recipe-tag";
export interface CreateRecipeBulk {
    url: string;
    categories?: Array<RecipeCategory> | null;
    tags?: Array<RecipeTag> | null;
}
