// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface CreateUserRegistration {
    group?: string | null;
    household?: string | null;
    groupToken?: string | null;
    email: string;
    username: string;
    fullName: string;
    password: string;
    passwordConfirm: string;
    advanced?: boolean;
    private?: boolean;
    seedData?: boolean;
    locale?: string;
}
