// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface CreateInviteToken {
    uses: number;
    groupId?: string | null;
    householdId?: string | null;
}
