// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { WebhookType } from "./webhook-type";
export interface CreateWebhook {
    enabled?: boolean;
    name?: string;
    url?: string;
    webhookType?: WebhookType;
    scheduledTime: string;
}
