// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { CreateRecipeBulk } from "./create-recipe-bulk";
export interface CreateRecipeByUrlBulk {
    imports: Array<CreateRecipeBulk>;
}
