// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { CreateIngredientUnitAlias } from "./create-ingredient-unit-alias";
export interface CreateIngredientUnit {
    id?: string | null;
    name: string;
    pluralName?: string | null;
    description?: string;
    extras?: Record<string, unknown> | null;
    fraction?: boolean;
    abbreviation?: string;
    pluralAbbreviation?: string | null;
    useAbbreviation?: boolean;
    aliases?: Array<CreateIngredientUnitAlias>;
    standardQuantity?: number | null;
    standardUnit?: string | null;
}
