// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ExportTypes } from "./export-types";
export interface ExportRecipes {
    recipes: Array<string>;
    exportType?: ExportTypes;
}
