// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { AIProviderSettingsOut } from "./aiprovider-settings-out";
import { ReadGroupPreferences } from "./read-group-preferences";
export interface GroupSummary {
    name: string;
    id: string;
    slug: string;
    preferences?: ReadGroupPreferences | null;
    aiProviderSettings?: AIProviderSettingsOut | null;
}
