// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { GroupEventNotifierOptionsOut } from "./group-event-notifier-options-out";
export interface GroupEventNotifierOut {
    id: string;
    name: string;
    enabled: boolean;
    groupId: string;
    householdId: string;
    options: GroupEventNotifierOptionsOut;
}
