// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { AIProviderSettingsOut } from "./aiprovider-settings-out";
import { CategoryBase } from "./category-base";
import { GroupHouseholdSummary } from "./group-household-summary";
import { ReadGroupPreferences } from "./read-group-preferences";
import { ReadWebhook } from "./read-webhook";
import { UserSummary } from "./user-summary";
export interface GroupInDB {
    name: string;
    id: string;
    slug: string;
    categories?: Array<CategoryBase> | null;
    webhooks?: Array<ReadWebhook>;
    households?: Array<GroupHouseholdSummary> | null;
    users?: Array<UserSummary> | null;
    preferences?: ReadGroupPreferences | null;
    aiProviderSettings?: AIProviderSettingsOut | null;
}
