// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { GroupEventNotifierOptions } from "./group-event-notifier-options";
export interface GroupEventNotifierUpdate {
    name: string;
    appriseUrl?: string | null;
    enabled?: boolean;
    groupId: string;
    householdId: string;
    options?: GroupEventNotifierOptions;
    id: string;
}
