// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface GroupEventNotifierOptionsOut {
    testMessage?: boolean;
    webhookTask?: boolean;
    recipeCreated?: boolean;
    recipeUpdated?: boolean;
    recipeDeleted?: boolean;
    userSignup?: boolean;
    dataMigrations?: boolean;
    dataExport?: boolean;
    dataImport?: boolean;
    mealplanEntryCreated?: boolean;
    mealplanEntryUpdated?: boolean;
    mealplanEntryDeleted?: boolean;
    shoppingListCreated?: boolean;
    shoppingListUpdated?: boolean;
    shoppingListDeleted?: boolean;
    cookbookCreated?: boolean;
    cookbookUpdated?: boolean;
    cookbookDeleted?: boolean;
    tagCreated?: boolean;
    tagUpdated?: boolean;
    tagDeleted?: boolean;
    categoryCreated?: boolean;
    categoryUpdated?: boolean;
    categoryDeleted?: boolean;
    labelCreated?: boolean;
    labelUpdated?: boolean;
    labelDeleted?: boolean;
    id: string;
}
