// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { AIProviderSettingsUpdate } from "./aiprovider-settings-update";
import { UpdateGroupPreferences } from "./update-group-preferences";
export interface GroupAdminUpdate {
    id: string;
    name: string;
    preferences?: UpdateGroupPreferences | null;
    aiProviderSettings?: AIProviderSettingsUpdate | null;
}
