// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { GroupRecipeActionOut } from "./group-recipe-action-out";
export interface GroupRecipeActionPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<GroupRecipeActionOut>;
    next?: string | null;
    previous?: string | null;
}
