// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ReadHouseholdPreferences } from "./read-household-preferences";
export interface HouseholdSummary {
    groupId: string;
    name: string;
    id: string;
    slug: string;
    preferences?: ReadHouseholdPreferences | null;
}
