// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface HouseholdStatistics {
    totalRecipes: number;
    totalUsers: number;
    totalCategories: number;
    totalTags: number;
    totalTools: number;
}
