// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HouseholdUserSummary } from "./household-user-summary";
import { ReadHouseholdPreferences } from "./read-household-preferences";
import { ReadWebhook } from "./read-webhook";
export interface HouseholdInDB {
    groupId: string;
    name: string;
    id: string;
    slug: string;
    preferences?: ReadHouseholdPreferences | null;
    group: string;
    users?: Array<HouseholdUserSummary> | null;
    webhooks?: Array<ReadWebhook>;
}
