// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HouseholdInDB } from "./household-in-db";
export interface HouseholdPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<HouseholdInDB>;
    next?: string | null;
    previous?: string | null;
}
