// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ValidationError } from "./validation-error";
export interface HTTPValidationError {
    detail?: Array<ValidationError>;
}
