// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export enum ImageType {
    OriginalWebp = "original.webp",
    MinOriginalWebp = "min-original.webp",
    TinyOriginalWebp = "tiny-original.webp"
}
