// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
/** A list of ingredient references. */
export interface IngredientReferences {
    referenceId?: string | null;
}
