// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { IngredientUnit_Output } from "./ingredient-unit-output";
export interface IngredientUnitPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<IngredientUnit_Output>;
    next?: string | null;
    previous?: string | null;
}
