// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { IngredientUnitAlias } from "./ingredient-unit-alias";
export interface IngredientUnit_Input {
    id: string;
    name: string;
    pluralName?: string | null;
    description?: string;
    extras?: Record<string, unknown> | null;
    fraction?: boolean;
    abbreviation?: string;
    pluralAbbreviation?: string | null;
    useAbbreviation?: boolean;
    aliases?: Array<IngredientUnitAlias>;
    standardQuantity?: number | null;
    standardUnit?: string | null;
    createdAt?: Date | null;
    update_at?: Date | null;
}
