// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { IngredientFoodAlias } from "./ingredient-food-alias";
import { MultiPurposeLabelSummary } from "./multi-purpose-label-summary";
export interface IngredientFood_Input {
    id: string;
    name: string;
    pluralName?: string | null;
    description?: string;
    extras?: Record<string, unknown> | null;
    labelId?: string | null;
    aliases?: Array<IngredientFoodAlias>;
    householdsWithIngredientFood?: Array<string>;
    label?: MultiPurposeLabelSummary | null;
    createdAt?: Date | null;
    update_at?: Date | null;
}
