// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RegisteredParser } from "./registered-parser";
export interface IngredientsRequest {
    parser?: RegisteredParser;
    ingredients: Array<string>;
}
