// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface IngredientConfidence {
    average?: number | null;
    comment?: number | null;
    name?: number | null;
    unit?: number | null;
    quantity?: number | null;
    food?: number | null;
}
