// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
/** Should ONLY be used when creating a new token, as the token field is sensitive */
export interface LongLiveTokenCreateResponse {
    name: string;
    id: number;
    createdAt?: Date | null;
    token: string;
}
