// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface MaintenanceStorageDetails {
    tempDirSize: string;
    backupsDirSize: string;
    groupsDirSize: string;
    recipesDirSize: string;
    userDirSize: string;
}
