// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface Mealie_Schema_Recipe_RecipeComments__UserBase {
    id: string;
    username?: string | null;
    admin: boolean;
    fullName?: string | null;
}
