// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
/** An authorization code captured by a native client, for server-side exchange. */
export interface NativeOIDCTokenRequest {
    code: string;
    code_verifier: string;
    redirect_uri: string;
    nonce?: string | null;
}
