// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface Nutrition {
    calories?: string | null;
    carbohydrateContent?: string | null;
    cholesterolContent?: string | null;
    fatContent?: string | null;
    fiberContent?: string | null;
    proteinContent?: string | null;
    saturatedFatContent?: string | null;
    sodiumContent?: string | null;
    sugarContent?: string | null;
    transFatContent?: string | null;
    unsaturatedFatContent?: string | null;
}
