// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
/** Parameters a native client needs to start an OIDC authorization request itself. */
export interface OIDCNativeConfig {
    authorization_endpoint: string;
    client_id: string;
    scope: string;
}
