// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { UserSummary } from "./user-summary";
export interface PaginationBase_UserSummary_ {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<UserSummary>;
    next?: string | null;
    previous?: string | null;
}
