// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeTag } from "./recipe-tag";
export interface PaginationBase_RecipeTag_ {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<RecipeTag>;
    next?: string | null;
    previous?: string | null;
}
