// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { IngredientFood_Output } from "./ingredient-food-output";
export interface PaginationBase_IngredientFood_ {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<IngredientFood_Output>;
    next?: string | null;
    previous?: string | null;
}
