// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeSummary } from "./recipe-summary";
export interface PaginationBase_RecipeSummary_ {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<RecipeSummary>;
    next?: string | null;
    previous?: string | null;
}
