// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { IngredientConfidence } from "./ingredient-confidence";
import { RecipeIngredient_Output } from "./recipe-ingredient-output";
export interface ParsedIngredient {
    input?: string | null;
    confidence?: IngredientConfidence;
    ingredient: RecipeIngredient_Output;
}
