// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { PlanRulesOut } from "./plan-rules-out";
export interface PlanRulesPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<PlanRulesOut>;
    next?: string | null;
    previous?: string | null;
}
