// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export enum PlanRulesType {
    Breakfast = "breakfast",
    Lunch = "lunch",
    Dinner = "dinner",
    Side = "side",
    Snack = "snack",
    Drink = "drink",
    Dessert = "dessert",
    Unset = "unset"
}
