// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { PlanRulesDay } from "./plan-rules-day";
import { PlanRulesType } from "./plan-rules-type";
export interface PlanRulesCreate {
    day?: PlanRulesDay;
    entryType?: PlanRulesType;
    queryFilterString?: string;
}
