// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { PlanRulesDay } from "./plan-rules-day";
import { PlanRulesType } from "./plan-rules-type";
import { QueryFilterJSON } from "./query-filter-json";
export interface PlanRulesOut {
    day?: PlanRulesDay;
    entryType?: PlanRulesType;
    queryFilterString?: string;
    groupId: string;
    householdId: string;
    id: string;
    queryFilter?: QueryFilterJSON;
}
