// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ReadPlanEntry } from "./read-plan-entry";
export interface PlanEntryPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<ReadPlanEntry>;
    next?: string | null;
    previous?: string | null;
}
