// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { LogicalOperator } from "./logical-operator";
import { RelationalKeyword } from "./relational-keyword";
import { RelationalOperator } from "./relational-operator";
export interface QueryFilterJSONPart {
    leftParenthesis?: string | null;
    rightParenthesis?: string | null;
    logicalOperator?: LogicalOperator | null;
    attributeName?: string | null;
    relationalOperator?: RelationalKeyword | RelationalOperator | null;
    value?: string | Array<string> | null;
}
