// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { QueryFilterJSONPart } from "./query-filter-jsonpart";
export interface QueryFilterJSON {
    parts?: Array<QueryFilterJSONPart>;
}
