// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface ReadGroupPreferences {
    privateGroup?: boolean;
    showAnnouncements?: boolean;
    groupId: string;
    id: string;
}
