// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { CookbookHousehold } from "./cookbook-household";
import { QueryFilterJSON } from "./query-filter-json";
export interface ReadCookBook {
    name: string;
    description?: string;
    slug?: string | null;
    position?: number;
    public?: boolean;
    queryFilterString?: string;
    groupId: string;
    householdId: string;
    id: string;
    queryFilter?: QueryFilterJSON;
    household?: CookbookHousehold | null;
}
