// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface ReadHouseholdPreferences {
    privateHousehold?: boolean;
    showAnnouncements?: boolean;
    lockRecipeEditsFromOtherHouseholds?: boolean;
    firstDayOfWeek?: number;
    recipePublic?: boolean;
    recipeShowNutrition?: boolean;
    recipeShowAssets?: boolean;
    recipeLandscapeView?: boolean;
    recipeDisableComments?: boolean;
    id: string;
}
