// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { PlanEntryType } from "./plan-entry-type";
import { RecipeSummary } from "./recipe-summary";
export interface ReadPlanEntry {
    date: Date;
    entryType?: PlanEntryType;
    title?: string;
    text?: string;
    recipeId?: string | null;
    id: number;
    groupId: string;
    userId: string;
    householdId: string;
    recipe?: RecipeSummary | null;
}
