// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface RecipeSettings {
    public?: boolean;
    showNutrition?: boolean;
    showAssets?: boolean;
    landscapeView?: boolean;
    disableComments?: boolean;
    locked?: boolean;
}
