// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeCommentOut_Output } from "./recipe-comment-out-output";
export interface RecipeCommentPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<RecipeCommentOut_Output>;
    next?: string | null;
    previous?: string | null;
}
