// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface RecipeToolOut {
    name: string;
    householdsWithTool?: Array<string>;
    id: string;
    groupId: string;
    slug: string;
}
