// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeTimelineEventOut } from "./recipe-timeline-event-out";
export interface RecipeTimelineEventPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<RecipeTimelineEventOut>;
    next?: string | null;
    previous?: string | null;
}
