// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { CreateIngredientFood } from "./create-ingredient-food";
import { CreateIngredientUnit } from "./create-ingredient-unit";
import { IngredientFood_Output } from "./ingredient-food-output";
import { IngredientUnit_Output } from "./ingredient-unit-output";
import { Recipe_Output } from "./recipe-output";
export interface RecipeIngredient_Output {
    quantity?: number | null;
    unit?: IngredientUnit_Output | CreateIngredientUnit | null;
    food?: IngredientFood_Output | CreateIngredientFood | null;
    referencedRecipe?: Recipe_Output | null;
    note?: string | null;
    display?: string;
    title?: string | null;
    originalText?: string | null;
    referenceId?: string;
}
