// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface RecipeShareTokenSummary {
    recipeId: string;
    expiresAt?: Date;
    groupId: string;
    id: string;
    createdAt: Date;
}
