// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { IngredientReferences } from "./ingredient-references";
export interface RecipeStep {
    id?: string | null;
    title?: string | null;
    summary?: string | null;
    text: string;
    ingredientReferences?: Array<IngredientReferences>;
}
