// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeSummary } from "./recipe-summary";
export interface RecipeTagResponse {
    name: string;
    id: string;
    groupId?: string | null;
    slug: string;
    recipes?: Array<RecipeSummary>;
}
