// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { UserBase_Output } from "./user-base-output";
export interface RecipeCommentOut_Output {
    recipeId: string;
    text: string;
    id: string;
    createdAt: Date;
    updatedAt: Date;
    userId: string;
    user: UserBase_Output;
}
