// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { Mealie_Schema_Recipe_RecipeComments__UserBase } from "./mealie-schema-recipe-recipe-comments-user-base";
export interface RecipeCommentOut_Input {
    recipeId: string;
    text: string;
    id: string;
    createdAt: Date;
    update_at: Date;
    userId: string;
    user: Mealie_Schema_Recipe_RecipeComments__UserBase;
}
