// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { Nutrition } from "./nutrition";
import { RecipeAsset } from "./recipe-asset";
import { RecipeCategory } from "./recipe-category";
import { RecipeCommentOut_Output } from "./recipe-comment-out-output";
import { RecipeIngredient_Output } from "./recipe-ingredient-output";
import { RecipeNote } from "./recipe-note";
import { RecipeSettings } from "./recipe-settings";
import { RecipeStep } from "./recipe-step";
import { RecipeTag } from "./recipe-tag";
import { RecipeTool } from "./recipe-tool";
export interface Recipe_Output {
    id?: string | null;
    userId?: string;
    householdId?: string;
    groupId?: string;
    name?: string | null;
    slug?: string;
    image?: null;
    recipeServings?: number;
    recipeYieldQuantity?: number;
    recipeYield?: string | null;
    totalTime?: string | null;
    prepTime?: string | null;
    cookTime?: string | null;
    performTime?: string | null;
    description?: string | null;
    recipeCategory?: Array<RecipeCategory> | null;
    tags?: Array<RecipeTag> | null;
    tools?: Array<RecipeTool>;
    rating?: number | null;
    orgURL?: string | null;
    dateAdded?: Date | null;
    dateUpdated?: Date | null;
    createdAt?: Date | null;
    updatedAt?: Date | null;
    lastMade?: Date | null;
    recipeIngredient?: Array<RecipeIngredient_Output>;
    recipeInstructions?: Array<RecipeStep> | null;
    nutrition?: Nutrition | null;
    settings?: RecipeSettings | null;
    assets?: Array<RecipeAsset> | null;
    notes?: Array<RecipeNote> | null;
    extras?: Record<string, unknown> | null;
    comments?: Array<RecipeCommentOut_Output> | null;
}
