// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { Recipe_Output } from "./recipe-output";
export interface RecipeShareToken {
    recipeId: string;
    expiresAt?: Date;
    groupId: string;
    id: string;
    createdAt: Date;
    recipe: Recipe_Output;
}
