// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { TimelineEventImage } from "./timeline-event-image";
import { TimelineEventType } from "./timeline-event-type";
export interface RecipeTimelineEventIn {
    recipeId: string;
    userId?: string | null;
    subject: string;
    eventType: TimelineEventType;
    eventMessage?: string | null;
    image?: TimelineEventImage | null;
    timestamp?: Date;
}
