// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { IngredientFood_Output } from "./ingredient-food-output";
import { RecipeSummary } from "./recipe-summary";
import { RecipeTool } from "./recipe-tool";
export interface RecipeSuggestionResponseItem {
    recipe: RecipeSummary;
    missingFoods: Array<IngredientFood_Output>;
    missingTools: Array<RecipeTool>;
}
