// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { TimelineEventImage } from "./timeline-event-image";
export interface RecipeTimelineEventUpdate {
    subject: string;
    eventMessage?: string | null;
    image?: TimelineEventImage | null;
}
