// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface RecipeCategory {
    id?: string | null;
    groupId?: string | null;
    name: string;
    slug: string;
}
