// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeCategory } from "./recipe-category";
import { RecipeTag } from "./recipe-tag";
import { RecipeTool } from "./recipe-tool";
export interface RecipeSummary {
    id?: string | null;
    userId?: string;
    householdId?: string;
    groupId?: string;
    name?: string | null;
    slug?: string;
    image?: null;
    recipeServings?: number;
    recipeYieldQuantity?: number;
    recipeYield?: string | null;
    totalTime?: string | null;
    prepTime?: string | null;
    cookTime?: string | null;
    performTime?: string | null;
    description?: string | null;
    recipeCategory?: Array<RecipeCategory> | null;
    tags?: Array<RecipeTag> | null;
    tools?: Array<RecipeTool>;
    rating?: number | null;
    orgURL?: string | null;
    dateAdded?: Date | null;
    dateUpdated?: Date | null;
    createdAt?: Date | null;
    updatedAt?: Date | null;
    lastMade?: Date | null;
}
