// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { CreateIngredientFood } from "./create-ingredient-food";
import { CreateIngredientUnit } from "./create-ingredient-unit";
import { IngredientFood_Input } from "./ingredient-food-input";
import { IngredientUnit_Input } from "./ingredient-unit-input";
import { Recipe_Input } from "./recipe-input";
export interface RecipeIngredient_Input {
    quantity?: number | null;
    unit?: IngredientUnit_Input | CreateIngredientUnit | null;
    food?: IngredientFood_Input | CreateIngredientFood | null;
    referencedRecipe?: Recipe_Input | null;
    note?: string | null;
    display?: string;
    title?: string | null;
    originalText?: string | null;
    referenceId?: string;
}
