// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export enum RelationalKeyword {
    IS = "IS",
    IS_NOT = "IS NOT",
    IN = "IN",
    NOT_IN = "NOT IN",
    CONTAINS_ALL = "CONTAINS ALL",
    LIKE = "LIKE",
    NOT_LIKE = "NOT LIKE"
}
