/* eslint-disable */
/* @formatter:off */
/**
 * Generated by ng-openapi, patched by RelationalOperatorPlugin.
 * Do not edit this file manually — it is overwritten on every generation.
 */
export enum RelationalOperator {
    EQ = "=",
    NOTEQ = "<>",
    GT = ">",
    LT = "<",
    GTE = ">=",
    LTE = "<="
}
