// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ReportCategory } from "./report-category";
import { ReportSummaryStatus } from "./report-summary-status";
export interface ReportSummary {
    timestamp?: Date;
    category: ReportCategory;
    groupId: string;
    name: string;
    status?: ReportSummaryStatus;
    id: string;
}
