// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { GroupRecipeActionType } from "./group-recipe-action-type";
export interface SaveGroupRecipeAction {
    actionType: GroupRecipeActionType;
    title: string;
    url: string;
    groupId: string;
    householdId: string;
}
