// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface SetPermissions {
    userId: string;
    canManageHousehold?: boolean;
    canManage?: boolean;
    canInvite?: boolean;
    canOrganize?: boolean;
}
