// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ShoppingListItemOut_Output } from "./shopping-list-item-out-output";
export interface ShoppingListItemPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<ShoppingListItemOut_Output>;
    next?: string | null;
    previous?: string | null;
}
