// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeIngredient_Input } from "./recipe-ingredient-input";
export interface ShoppingListAddRecipeParamsBulk {
    recipeIncrementQuantity?: number;
    recipeIngredients?: Array<RecipeIngredient_Input> | null;
    recipeId: string;
}
