// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { RecipeSummary } from "./recipe-summary";
export interface ShoppingListRecipeRefOut {
    id: string;
    shoppingListId: string;
    recipeId: string;
    recipeQuantity: number;
    recipe: RecipeSummary;
}
