// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { MultiPurposeLabelSummary } from "./multi-purpose-label-summary";
export interface ShoppingListMultiPurposeLabelOut {
    shoppingListId: string;
    labelId: string;
    position?: number;
    id: string;
    label: MultiPurposeLabelSummary;
}
