// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ShoppingListItemOut_Input } from "./shopping-list-item-out-input";
export interface ShoppingListUpdate {
    name?: string | null;
    extras?: Record<string, unknown> | null;
    createdAt?: Date | null;
    update_at?: Date | null;
    groupId: string;
    userId: string;
    id: string;
    listItems?: Array<ShoppingListItemOut_Input>;
}
