// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { CreateIngredientFood } from "./create-ingredient-food";
import { CreateIngredientUnit } from "./create-ingredient-unit";
import { IngredientFood_Input } from "./ingredient-food-input";
import { IngredientUnit_Input } from "./ingredient-unit-input";
import { Recipe_Input } from "./recipe-input";
import { ShoppingListItemRecipeRefCreate } from "./shopping-list-item-recipe-ref-create";
import { ShoppingListItemRecipeRefUpdate } from "./shopping-list-item-recipe-ref-update";
/** Only used for bulk update operations where the shopping list item id isn't already supplied */
export interface ShoppingListItemUpdateBulk {
    quantity?: number;
    unit?: IngredientUnit_Input | CreateIngredientUnit | null;
    food?: IngredientFood_Input | CreateIngredientFood | null;
    referencedRecipe?: Recipe_Input | null;
    note?: string | null;
    display?: string;
    shoppingListId: string;
    checked?: boolean;
    position?: number;
    foodId?: string | null;
    labelId?: string | null;
    unitId?: string | null;
    extras?: Record<string, unknown> | null;
    recipeReferences?: Array<ShoppingListItemRecipeRefCreate | ShoppingListItemRecipeRefUpdate>;
    id: string;
}
