// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface ShoppingListCreate {
    name?: string | null;
    extras?: Record<string, unknown> | null;
    createdAt?: Date | null;
    update_at?: Date | null;
}
