// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ShoppingListSummary } from "./shopping-list-summary";
export interface ShoppingListPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<ShoppingListSummary>;
    next?: string | null;
    previous?: string | null;
}
