// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ShoppingListItemOut_Output } from "./shopping-list-item-out-output";
/** Container for bulk shopping list item changes */
export interface ShoppingListItemsCollectionOut {
    createdItems?: Array<ShoppingListItemOut_Output>;
    updatedItems?: Array<ShoppingListItemOut_Output>;
    deletedItems?: Array<ShoppingListItemOut_Output>;
}
