// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { IngredientFood_Output } from "./ingredient-food-output";
import { IngredientUnit_Output } from "./ingredient-unit-output";
import { MultiPurposeLabelSummary } from "./multi-purpose-label-summary";
import { Recipe_Output } from "./recipe-output";
import { ShoppingListItemRecipeRefOut } from "./shopping-list-item-recipe-ref-out";
export interface ShoppingListItemOut_Output {
    quantity?: number;
    unit?: IngredientUnit_Output | null;
    food?: IngredientFood_Output | null;
    referencedRecipe?: Recipe_Output | null;
    note?: string | null;
    display?: string;
    shoppingListId: string;
    checked?: boolean;
    position?: number;
    foodId?: string | null;
    labelId?: string | null;
    unitId?: string | null;
    extras?: Record<string, unknown> | null;
    id: string;
    groupId: string;
    householdId: string;
    label?: MultiPurposeLabelSummary | null;
    recipeReferences?: Array<ShoppingListItemRecipeRefOut>;
    createdAt?: Date | null;
    updatedAt?: Date | null;
}
