// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ShoppingListMultiPurposeLabelOut } from "./shopping-list-multi-purpose-label-out";
import { ShoppingListRecipeRefOut } from "./shopping-list-recipe-ref-out";
export interface ShoppingListSummary {
    name?: string | null;
    extras?: Record<string, unknown> | null;
    createdAt?: Date | null;
    updatedAt?: Date | null;
    groupId: string;
    userId: string;
    id: string;
    householdId: string;
    recipeReferences: Array<ShoppingListRecipeRefOut>;
    labelSettings: Array<ShoppingListMultiPurposeLabelOut>;
}
