// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface ShoppingListMultiPurposeLabelUpdate {
    shoppingListId: string;
    labelId: string;
    position?: number;
    id: string;
}
