// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface ShoppingListItemRecipeRefOut {
    recipeId: string;
    recipeQuantity?: number;
    recipeScale?: number | null;
    recipeNote?: string | null;
    id: string;
    shoppingListItemId: string;
}
