// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export enum SupportedMigrations {
    Nextcloud = "nextcloud",
    Chowdown = "chowdown",
    Copymethat = "copymethat",
    Paprika = "paprika",
    MealieAlpha = "mealie_alpha",
    Tandoor = "tandoor",
    Plantoeat = "plantoeat",
    Myrecipebox = "myrecipebox",
    Recipekeeper = "recipekeeper",
    Cookn = "cookn"
}
