// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { UpdateHouseholdPreferences } from "./update-household-preferences";
export interface UpdateHouseholdAdmin {
    groupId: string;
    name: string;
    id: string;
    preferences?: UpdateHouseholdPreferences | null;
}
