// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { UserRatingSummary } from "./user-rating-summary";
export interface UserRatings_UserRatingSummary_ {
    ratings: Array<UserRatingSummary>;
}
