// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { AuthMethod } from "./auth-method";
export interface UserIn {
    id?: string | null;
    username: string;
    fullName: string;
    email: string;
    authMethod?: AuthMethod;
    admin?: boolean;
    group?: string | null;
    household?: string | null;
    advanced?: boolean;
    showAnnouncements?: boolean;
    lastReadAnnouncement?: string | null;
    canInvite?: boolean;
    canManage?: boolean;
    canManageHousehold?: boolean;
    canOrganize?: boolean;
    password: string;
}
