// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { AuthMethod } from "./auth-method";
import { LongLiveTokenOut } from "./long-live-token-out";
export interface UserOut {
    id: string;
    username?: string | null;
    fullName?: string | null;
    email: string;
    authMethod?: AuthMethod;
    admin?: boolean;
    group: string;
    household: string;
    advanced?: boolean;
    showAnnouncements?: boolean;
    lastReadAnnouncement?: string | null;
    canInvite?: boolean;
    canManage?: boolean;
    canManageHousehold?: boolean;
    canOrganize?: boolean;
    groupId: string;
    groupSlug: string;
    householdId: string;
    householdSlug: string;
    tokens?: Array<LongLiveTokenOut> | null;
    cacheKey: string;
}
