// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { UserRatingOut } from "./user-rating-out";
export interface UserRatings_UserRatingOut_ {
    ratings: Array<UserRatingOut>;
}
