// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface UserRatingOut {
    recipeId: string;
    rating?: number | null;
    isFavorite?: boolean;
    userId: string;
    id: string;
}
