// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { UserOut } from "./user-out";
export interface UserPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<UserOut>;
    next?: string | null;
    previous?: string | null;
}
