// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
export interface ValidationError {
    loc: Array<string | number>;
    msg: string;
    type: string;
    input?: any;
    ctx?: Record<string, unknown>;
}
