// @ts-nocheck
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { ReadWebhook } from "./read-webhook";
export interface WebhookPagination {
    page?: number;
    per_page?: number;
    total?: number;
    total_pages?: number;
    items: Array<ReadWebhook>;
    next?: string | null;
    previous?: string | null;
}
